package triggers

import (
	accountingtriggersql "notezy-backend/app/models/schemas/triggers/accounting_triggers"
	maintainingblocktriggers "notezy-backend/app/models/schemas/triggers/maintaining_block_triggers"
	shelfmaterialcascadingtriggersql "notezy-backend/app/models/schemas/triggers/shelf_material_cascading_triggers"
)

var MigratingTriggerSQLs = []string{
	shelfmaterialcascadingtriggersql.CascadingSoftDeleteRootShelfTriggerSQL,
	shelfmaterialcascadingtriggersql.CascadingSoftDeleteSubShelfTriggerSQL,
	shelfmaterialcascadingtriggersql.CascadingRestoreRootShelfTriggerSQL,
	shelfmaterialcascadingtriggersql.CascadingRestoreSubShelfTriggerSQL,
	shelfmaterialcascadingtriggersql.CascadingMoveSubShelfTriggerSQL,
	accountingtriggersql.AccountingMutatedBlockPackTriggerSQL,
	accountingtriggersql.AccountingInsertedBlockTriggerSQL,
	accountingtriggersql.AccountingDeletedBlockTriggerSQL,
	accountingtriggersql.AccountingMutatedRootShelfTriggerSQL,
	accountingtriggersql.AccountingMutatedSubShelfTriggerSQL,
	accountingtriggersql.AccountingMutatedMaterialTriggerSQL,
	maintainingblocktriggers.MaintainingFinalBlockGroupOnInsertTriggerSQL,
	maintainingblocktriggers.MaintainingFinalBlockGroupOnUpdateTriggerSQL,
	maintainingblocktriggers.MaintainingFinalBlockGroupOnDeleteTriggerSQL,
}
