package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	blockpackscontract "github.com/HiIamJeff67/notezy-backend/contracts/core/v1/api/block-packs"
	blockscontract "github.com/HiIamJeff67/notezy-backend/contracts/core/v1/api/blocks"
	itemscontract "github.com/HiIamJeff67/notezy-backend/contracts/core/v1/api/items"
	materialscontract "github.com/HiIamJeff67/notezy-backend/contracts/core/v1/api/materials"
	rootshelvescontract "github.com/HiIamJeff67/notezy-backend/contracts/core/v1/api/root-shelves"
	routinetagscontract "github.com/HiIamJeff67/notezy-backend/contracts/core/v1/api/routine-tags"
	routinetaskrecordscontract "github.com/HiIamJeff67/notezy-backend/contracts/core/v1/api/routine-task-records"
	routinetaskscontract "github.com/HiIamJeff67/notezy-backend/contracts/core/v1/api/routine-tasks"
	routinescontract "github.com/HiIamJeff67/notezy-backend/contracts/core/v1/api/routines"
	stationscontract "github.com/HiIamJeff67/notezy-backend/contracts/core/v1/api/stations"
	subshelvescontract "github.com/HiIamJeff67/notezy-backend/contracts/core/v1/api/sub-shelves"
	themescontract "github.com/HiIamJeff67/notezy-backend/contracts/core/v1/api/themes"
	userscontract "github.com/HiIamJeff67/notezy-backend/contracts/core/v1/api/users"
	"github.com/HiIamJeff67/notezy-backend/contracts/core/v1/graphql/generated"
	gqlmodels "github.com/HiIamJeff67/notezy-backend/contracts/core/v1/graphql/models"
	gatewaycontexts "github.com/HiIamJeff67/notezy-backend/internal/gateway/contexts"
	coreadapters "github.com/HiIamJeff67/notezy-backend/internal/gateway/transports/core/adapters"
	"github.com/HiIamJeff67/notezy-backend/shared/util/exceptionwriter"
)

// SearchUsers is the resolver for the searchUsers field.
func (r *queryResolver) SearchUsers(ctx context.Context, input gqlmodels.SearchUserInput) (*gqlmodels.SearchUserConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.CallSecurly[
		userscontract.SearchUsersRequestDto,
		userscontract.SearchUsersResponseDto,
	](
		ginContext,
		r.coreClient,
		&input,
		userscontract.SearchUsersOperation,
		"/core/v1/users/graphql/search",
	)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// SearchThemes is the resolver for the searchThemes field.
func (r *queryResolver) SearchThemes(ctx context.Context, input gqlmodels.SearchThemeInput) (*gqlmodels.SearchThemeConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.Call[
		themescontract.SearchThemesRequestDto,
		themescontract.SearchThemesResponseDto,
	](
		ginContext,
		r.coreClient,
		&input,
		themescontract.SearchThemesOperation,
		"/core/v1/themes/graphql/search",
	)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// SearchRootShelves is the resolver for the searchRootShelves field.
func (r *queryResolver) SearchRootShelves(ctx context.Context, input gqlmodels.SearchRootShelfInput) (*gqlmodels.SearchRootShelfConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.CallSecurly[
		rootshelvescontract.SearchRootShelvesRequestDto,
		rootshelvescontract.SearchRootShelvesResponseDto,
	](
		ginContext,
		r.coreClient,
		&input,
		rootshelvescontract.SearchRootShelvesOperation,
		"/core/v1/root-shelves/graphql/search",
	)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// SearchSubShelves is the resolver for the searchSubShelves field.
func (r *queryResolver) SearchSubShelves(ctx context.Context, input gqlmodels.SearchSubShelfInput) (*gqlmodels.SearchSubShelfConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.CallSecurly[
		subshelvescontract.SearchSubShelvesRequestDto,
		subshelvescontract.SearchSubShelvesResponseDto,
	](
		ginContext,
		r.coreClient,
		&input,
		subshelvescontract.SearchSubShelvesOperation,
		"/core/v1/sub-shelves/graphql/search",
	)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// SearchItems is the resolver for the searchItems field.
func (r *queryResolver) SearchItems(ctx context.Context, input gqlmodels.SearchItemInput) (*gqlmodels.SearchItemConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.CallSecurly[
		itemscontract.SearchItemsRequestDto,
		itemscontract.SearchItemsResponseDto,
	](
		ginContext,
		r.coreClient,
		&input,
		itemscontract.SearchItemsOperation,
		"/core/v1/items/graphql/search",
	)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// SearchMaterials is the resolver for the searchMaterials field.
func (r *queryResolver) SearchMaterials(ctx context.Context, input gqlmodels.SearchMaterialInput) (*gqlmodels.SearchMaterialConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.CallSecurly[
		materialscontract.SearchMaterialsRequestDto,
		materialscontract.SearchMaterialsResponseDto,
	](
		ginContext,
		r.coreClient,
		&input,
		materialscontract.SearchMaterialsOperation,
		"/core/v1/materials/graphql/search",
	)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// SearchBlockPacks is the resolver for the searchBlockPacks field.
func (r *queryResolver) SearchBlockPacks(ctx context.Context, input gqlmodels.SearchBlockPackInput) (*gqlmodels.SearchBlockPackConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.CallSecurly[
		blockpackscontract.SearchBlockPacksRequestDto,
		blockpackscontract.SearchBlockPacksResponseDto,
	](
		ginContext,
		r.coreClient,
		&input,
		blockpackscontract.SearchBlockPacksOperation,
		"/core/v1/block-packs/graphql/search",
	)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// SearchBlocks is the resolver for the searchBlocks field.
func (r *queryResolver) SearchBlocks(ctx context.Context, input gqlmodels.SearchBlockInput) (*gqlmodels.SearchBlockConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.CallSecurly[
		blockscontract.SearchBlocksRequestDto,
		blockscontract.SearchBlocksResponseDto,
	](
		ginContext,
		r.coreClient,
		&input,
		blockscontract.SearchBlocksOperation,
		"/core/v1/blocks/graphql/search",
	)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// SearchStations is the resolver for the searchStations field.
func (r *queryResolver) SearchStations(ctx context.Context, input gqlmodels.SearchStationInput) (*gqlmodels.SearchStationConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.CallSecurly[
		stationscontract.SearchStationsRequestDto,
		stationscontract.SearchStationsResponseDto,
	](
		ginContext,
		r.coreClient,
		&input,
		stationscontract.SearchStationsOperation,
		"/core/v1/stations/graphql/search",
	)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// SearchRoutines is the resolver for the searchRoutines field.
func (r *queryResolver) SearchRoutines(ctx context.Context, input gqlmodels.SearchRoutineInput) (*gqlmodels.SearchRoutineConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.CallSecurly[
		routinescontract.SearchRoutinesRequestDto,
		routinescontract.SearchRoutinesResponseDto,
	](
		ginContext,
		r.coreClient,
		&input,
		routinescontract.SearchRoutinesOperation,
		"/core/v1/routines/graphql/search",
	)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// SearchRoutineTags is the resolver for the searchRoutineTags field.
func (r *queryResolver) SearchRoutineTags(ctx context.Context, input gqlmodels.SearchRoutineTagInput) (*gqlmodels.SearchRoutineTagConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.CallSecurly[
		routinetagscontract.SearchRoutineTagsRequestDto,
		routinetagscontract.SearchRoutineTagsResponseDto,
	](
		ginContext,
		r.coreClient,
		&input,
		routinetagscontract.SearchRoutineTagsOperation,
		"/core/v1/routine-tags/graphql/search",
	)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// SearchRoutineTasks is the resolver for the searchRoutineTasks field.
func (r *queryResolver) SearchRoutineTasks(ctx context.Context, input gqlmodels.SearchRoutineTaskInput) (*gqlmodels.SearchRoutineTaskConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.CallSecurly[
		routinetaskscontract.SearchRoutineTasksRequestDto,
		routinetaskscontract.SearchRoutineTasksResponseDto,
	](
		ginContext,
		r.coreClient,
		&input,
		routinetaskscontract.SearchRoutineTasksOperation,
		"/core/v1/routine-tasks/graphql/search",
	)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// SearchRoutineTaskRecords is the resolver for the searchRoutineTaskRecords field.
func (r *queryResolver) SearchRoutineTaskRecords(ctx context.Context, input gqlmodels.SearchRoutineTaskRecordInput) (*gqlmodels.SearchRoutineTaskRecordConnection, error) {
	ginContext, exception := gatewaycontexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	response, exception := coreadapters.CallSecurly[
		routinetaskrecordscontract.SearchRoutineTaskRecordsRequestDto,
		routinetaskrecordscontract.SearchRoutineTaskRecordsResponseDto,
	](
		ginContext,
		r.coreClient,
		&input,
		routinetaskrecordscontract.SearchRoutineTaskRecordsOperation,
		"/core/v1/routine-task-records/graphql/search",
	)
	if exception != nil {
		return nil, exceptionwriter.ToGraphQLError(exception, ctx)
	}

	return &response.Data, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
