FROM golang:1.26-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
COPY internal/gateway/go.mod internal/gateway/go.sum internal/gateway/
COPY internal/durablejob/go.mod internal/durablejob/go.sum internal/durablejob/
COPY internal/email/go.mod internal/email/go.sum internal/email/
COPY internal/realtimegateway/go.mod internal/realtimegateway/go.sum internal/realtimegateway/
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o api ./cmd/api \
	&& CGO_ENABLED=0 GOOS=linux go build -o core ./cmd/core \
	&& CGO_ENABLED=0 GOOS=linux go build -o durablejob ./cmd/durablejob \
	&& CGO_ENABLED=0 GOOS=linux go build -o email ./cmd/email \
	&& CGO_ENABLED=0 GOOS=linux go build -o realtimegateway ./cmd/realtimegateway

FROM alpine:latest

WORKDIR /app

RUN apk --no-cache add ca-certificates

COPY --from=builder /app/api .
COPY --from=builder /app/core .
COPY --from=builder /app/durablejob .
COPY --from=builder /app/email .
COPY --from=builder /app/realtimegateway .

EXPOSE 7777

CMD ["./api"]
