FROM golang:1.24.2-alpine

RUN apk add --no-cache git

WORKDIR /notezy-backend

# copy go mod & go sum files
COPY go.mod go.sum ./

# download go modules & dependencies
RUN go mod tidy

# install Air (Go hot loading tool) !after downloading go mod
# instead of using the latest version which required golang:1.25
RUN go install github.com/air-verse/air@v1.61.7

# copy entire codes
COPY . .

# expose the port
EXPOSE 7777

# use Air to processing hot loading
CMD ["air", "-c", ".air.toml"]