FROM golang:1.26-alpine

RUN apk add --no-cache git

WORKDIR /notezy-backend

# copy go mod & go sum files
COPY go.mod go.sum ./
COPY internal/gateway/go.mod internal/gateway/go.sum internal/gateway/
COPY internal/durablejob/go.mod internal/durablejob/go.sum internal/durablejob/
COPY internal/email/go.mod internal/email/go.sum internal/email/
COPY internal/realtimegateway/go.mod internal/realtimegateway/go.sum internal/realtimegateway/

# download go modules & dependencies
RUN go mod tidy

# install Air (Go hot loading tool) !after downloading go mod
RUN go install github.com/air-verse/air@latest

# copy entire codes
COPY . .

# expose the port
EXPOSE 7777

# use Air to processing hot loading
CMD ["air", "-c", ".air.toml"]
