FROM golang:1.24.2-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o api ./cmd/api \
	&& CGO_ENABLED=0 GOOS=linux go build -o durablejob ./cmd/durablejob \
	&& CGO_ENABLED=0 GOOS=linux go build -o email ./cmd/email

FROM alpine:latest

WORKDIR /app

RUN apk --no-cache add ca-certificates

COPY --from=builder /app/api .
COPY --from=builder /app/durablejob .
COPY --from=builder /app/email .

EXPOSE 7777

CMD ["./api"]
