package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"notezy-backend/app/contexts"
	"notezy-backend/app/graphql/generated"
	gqlmodels "notezy-backend/app/graphql/models"
	"notezy-backend/shared/constants"
)

// SearchUsers is the resolver for the searchUsers field.
func (r *queryResolver) SearchUsers(ctx context.Context, input gqlmodels.SearchUserInput) (*gqlmodels.SearchUserConnection, error) {
	result, exception := r.userService.SearchPublicUsers(ctx, input)
	if exception != nil {
		return nil, exception.Log().ToGraphQLError(ctx)
	}

	return result, nil
}

// SearchThemes is the resolver for the searchThemes field.
func (r *queryResolver) SearchThemes(ctx context.Context, input gqlmodels.SearchThemeInput) (*gqlmodels.SearchThemeConnection, error) {
	result, exception := r.themeService.SearchPublicThemes(ctx, input)
	if exception != nil {
		return nil, exception.Log().ToGraphQLError(ctx)
	}

	return result, nil
}

// SearchRootShelves is the resolver for the searchRootShelves field.
func (r *queryResolver) SearchRootShelves(ctx context.Context, input gqlmodels.SearchRootShelfInput) (*gqlmodels.SearchRootShelfConnection, error) {
	ginContext, exception := contexts.GetAndConvertContextToGinContext(ctx)
	if exception != nil {
		return nil, exception.Log().ToGraphQLError(ctx)
	}

	userId, exception := contexts.GetAndConvertContextFieldToUUID(ginContext, constants.ContextFieldName_User_Id)
	if exception != nil {
		exception.Log().SafelyResponseWithJSON(ginContext)
		return nil, exception.Log().ToGraphQLError(ctx)
	}
	result, exception := r.rootShelfService.SearchPrivateShelves(ctx, *userId, input)
	if exception != nil {
		return nil, exception.Log().ToGraphQLError(ctx)
	}

	return result, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
