dictionaries = ["en_us"]

ignore_patterns = [
  '[nN][oO][tT][eE][zZ][yY][a-zA-Z]*',
  'go[a-zA-Z]*',
  'gorm',
  'gin',
  'gin-[a-zA-Z]*',
  'endless',
  'is[a-z]+',
  'English',
  'Enterprise',
  'go-randomdata',
  '[a-zA-Z0-9]*sql',
  'sdk[a-zA-Z0-9]*',
  '[a-zA-Z0-9]*routes',
  'otl[a-zA-Z]*',
]

words = [
    "notezy",
    "notezyDB",
    "trancate",
    "endless",
    "modcache",
    "hotreload",
    "gin",
    "gorm",
    "dto",
    "dtos",
    "comail",
    "colog",
    "fileln",
    "NANP",
    "appendonly",
    "healthcheck",
    "alphanum",
    "alphaandnum",
    "timestamptz",
    "dbname",
    "sslmode",
    "enumlabel",
    "enumtypid",
    "enumsortorder",
    "serial",
    "pallinder",
    "randomdata",
    "gqlerror",
    "jinzhu",
    "searchcursor",
    "responsewriter",
    "gql",
    "gqlmodels",
    "gqlgen",
    "gqlparser",
    "cending",
    "vektah",
    "cjson",
    "blocknote",
    "datatypes",
    "datatype",
    "omitnil",
    "istoggleable",
    "otelcol",
    "rowspan",
    "colspan",
    "parentblockid",
    "semconv",
    "fvbock",
    "strs",
    "presign",
    "froms",
    "fcall",
    "notfuture",
    "notpast",
    "refreshable",
    "vbscript",
    "authe2etest",
    "println",
    "mutatable",
    "accessable",
    "reappend",
    "maintainingblocktriggers",
    "routinetask",
    "durablejob",
    "durablejobs",
    "matchers",
    "arborized",
    "yjs",
    "realtimetypes",
]

ignore_paths = [
  "vendor/**/*",
  "node_modules/**/*",
  "build/**/*",
  "target/**/*",
  ".git/**/*",
]
