id = "notezy-snippets"
name = "Notezy Snippets"
version = "0.1.0"
schema_version = 1
authors = ["Jeff"]
description = "Project snippets for notezy-backend"
repository = "https://github.com/HiIamJeff67/notezy-backend"
snippets = ["./snippets/snippets.json", "./snippets/go.json"]
