id = "notegic-snippets"
name = "Notegic Snippets"
version = "0.1.0"
schema_version = 1
authors = ["Jeff"]
description = "Project snippets for notegic-backend"
repository = "https://github.com/HiIamJeff67/notegic-backend"
snippets = ["./snippets/snippets.json", "./snippets/go.json"]
