package routers

import (
	"github.com/gin-gonic/gin"

	rootshelvesdto "github.com/HiIamJeff67/notezy-backend/contracts/core/v1/api/root-shelves"

	endpoints "github.com/HiIamJeff67/notezy-backend/internal/core/transports/gateway/endpoints"
	middlewares "github.com/HiIamJeff67/notezy-backend/internal/core/transports/gateway/middlewares"
)

func configureRootShelfRoutes(
	router *gin.RouterGroup,
	authMiddleware gin.HandlerFunc,
	endpoint endpoints.RootShelfEndpointInterface,
) {
	rootShelfRoutes := router.Group("/root-shelves")
	{
		rootShelfRoutes.POST(
			"/get-by-id",
			middlewares.DelegationAuthenticatedMiddleware(
				rootshelvesdto.GetMyRootShelfByIdOperation,
			),
			authMiddleware,
			endpoint.GetMyRootShelfById,
		)
		rootShelfRoutes.POST(
			"/create",
			middlewares.DelegationAuthenticatedMiddleware(
				rootshelvesdto.CreateRootShelfOperation,
			),
			authMiddleware,
			endpoint.CreateRootShelf,
		)
		rootShelfRoutes.POST(
			"/create-many",
			middlewares.DelegationAuthenticatedMiddleware(
				rootshelvesdto.CreateRootShelvesOperation,
			),
			authMiddleware,
			endpoint.CreateRootShelves,
		)
		rootShelfRoutes.POST(
			"/update",
			middlewares.DelegationAuthenticatedMiddleware(
				rootshelvesdto.UpdateMyRootShelfByIdOperation,
			),
			authMiddleware,
			endpoint.UpdateMyRootShelfById,
		)
		rootShelfRoutes.POST(
			"/update-many",
			middlewares.DelegationAuthenticatedMiddleware(
				rootshelvesdto.UpdateMyRootShelvesByIdsOperation,
			),
			authMiddleware,
			endpoint.UpdateMyRootShelvesByIds,
		)
		rootShelfRoutes.POST(
			"/restore",
			middlewares.DelegationAuthenticatedMiddleware(
				rootshelvesdto.RestoreMyRootShelfByIdOperation,
			),
			authMiddleware,
			endpoint.RestoreMyRootShelfById,
		)
		rootShelfRoutes.POST(
			"/restore-many",
			middlewares.DelegationAuthenticatedMiddleware(
				rootshelvesdto.RestoreMyRootShelvesByIdsOperation,
			),
			authMiddleware,
			endpoint.RestoreMyRootShelvesByIds,
		)
		rootShelfRoutes.POST(
			"/delete",
			middlewares.DelegationAuthenticatedMiddleware(
				rootshelvesdto.DeleteMyRootShelfByIdOperation,
			),
			authMiddleware,
			endpoint.DeleteMyRootShelfById,
		)
		rootShelfRoutes.POST(
			"/delete-many",
			middlewares.DelegationAuthenticatedMiddleware(
				rootshelvesdto.DeleteMyRootShelvesByIdsOperation,
			),
			authMiddleware,
			endpoint.DeleteMyRootShelvesByIds,
		)
		rootShelfRoutes.POST(
			"/permissions/get",
			middlewares.DelegationAuthenticatedMiddleware(
				rootshelvesdto.GetMyRootShelfPermissionOperation,
			),
			authMiddleware,
			endpoint.GetMyRootShelfPermission,
		)
		rootShelfRoutes.POST(
			"/permissions/create",
			middlewares.DelegationAuthenticatedMiddleware(
				rootshelvesdto.CreateMyRootShelfPermissionOperation,
			),
			authMiddleware,
			endpoint.CreateMyRootShelfPermission,
		)
		rootShelfRoutes.POST(
			"/permissions/upsert",
			middlewares.DelegationAuthenticatedMiddleware(
				rootshelvesdto.UpsertMyRootShelfPermissionOperation,
			),
			authMiddleware,
			endpoint.UpsertMyRootShelfPermission,
		)
		rootShelfRoutes.POST(
			"/permissions/upsert-many",
			middlewares.DelegationAuthenticatedMiddleware(
				rootshelvesdto.UpsertMyRootShelfPermissionsOperation,
			),
			authMiddleware,
			endpoint.UpsertMyRootShelfPermissions,
		)
		rootShelfRoutes.POST(
			"/permissions/update",
			middlewares.DelegationAuthenticatedMiddleware(
				rootshelvesdto.UpdateMyRootShelfPermissionOperation,
			),
			authMiddleware,
			endpoint.UpdateMyRootShelfPermission,
		)
		rootShelfRoutes.POST(
			"/ownership/transfer",
			middlewares.DelegationAuthenticatedMiddleware(
				rootshelvesdto.TransferMyRootShelfOwnershipOperation,
			),
			authMiddleware,
			endpoint.TransferMyRootShelfOwnership,
		)
		rootShelfRoutes.POST(
			"/permissions/delete",
			middlewares.DelegationAuthenticatedMiddleware(
				rootshelvesdto.DeleteMyRootShelfPermissionOperation,
			),
			authMiddleware,
			endpoint.DeleteMyRootShelfPermission,
		)
		rootShelfRoutes.POST(
			"/permissions/delete-many",
			middlewares.DelegationAuthenticatedMiddleware(
				rootshelvesdto.DeleteMyRootShelfPermissionsOperation,
			),
			authMiddleware,
			endpoint.DeleteMyRootShelfPermissions,
		)
		rootShelfRoutes.POST(
			"/memberships/leave",
			middlewares.DelegationAuthenticatedMiddleware(
				rootshelvesdto.LeaveMyRootShelfOperation,
			),
			authMiddleware,
			endpoint.LeaveMyRootShelf,
		)
		rootShelfRoutes.POST(
			"/memberships/leave-many",
			middlewares.DelegationAuthenticatedMiddleware(
				rootshelvesdto.LeaveMyRootShelvesOperation,
			),
			authMiddleware,
			endpoint.LeaveMyRootShelves,
		)
		rootShelfRoutes.POST(
			"/graphql/search",
			middlewares.DelegationAuthenticatedMiddleware(
				rootshelvesdto.SearchRootShelvesOperation,
			),
			authMiddleware,
			endpoint.SearchRootShelves,
		)
	}
}
