package routers

import (
	"github.com/gin-gonic/gin"

	routinesdto "github.com/HiIamJeff67/notezy-backend/contracts/core/v1/api/routines"

	endpoints "github.com/HiIamJeff67/notezy-backend/internal/core/transports/gateway/endpoints"
	middlewares "github.com/HiIamJeff67/notezy-backend/internal/core/transports/gateway/middlewares"
)

func configureRoutineRoutes(
	router *gin.RouterGroup,
	authMiddleware gin.HandlerFunc,
	endpoint endpoints.RoutineEndpointInterface,
) {
	routineRoutes := router.Group("/routines")
	{
		routineRoutes.POST(
			"/get-by-id",
			middlewares.DelegationAuthenticatedMiddleware(
				routinesdto.GetMyRoutineByIdOperation,
			),
			authMiddleware,
			endpoint.GetMyRoutineById,
		)
		routineRoutes.POST(
			"/get-by-station-id",
			middlewares.DelegationAuthenticatedMiddleware(
				routinesdto.GetMyRoutinesByStationIdOperation,
			),
			authMiddleware,
			endpoint.GetMyRoutinesByStationId,
		)
		routineRoutes.POST(
			"/get-all-by-time-range",
			middlewares.DelegationAuthenticatedMiddleware(
				routinesdto.GetAllMyRoutinesByTimeRangeOperation,
			),
			authMiddleware,
			endpoint.GetAllMyRoutinesByTimeRange,
		)
		routineRoutes.POST(
			"/create-by-station-id",
			middlewares.DelegationAuthenticatedMiddleware(
				routinesdto.CreateRoutineByStationIdOperation,
			),
			authMiddleware,
			endpoint.CreateRoutineByStationId,
		)
		routineRoutes.POST(
			"/create-many-by-station-ids",
			middlewares.DelegationAuthenticatedMiddleware(
				routinesdto.CreateRoutinesByStationIdsOperation,
			),
			authMiddleware,
			endpoint.CreateRoutinesByStationIds,
		)
		routineRoutes.POST(
			"/update",
			middlewares.DelegationAuthenticatedMiddleware(
				routinesdto.UpdateMyRoutineByIdOperation,
			),
			authMiddleware,
			endpoint.UpdateMyRoutineById,
		)
		routineRoutes.POST(
			"/update-many",
			middlewares.DelegationAuthenticatedMiddleware(
				routinesdto.UpdateMyRoutinesByIdsOperation,
			),
			authMiddleware,
			endpoint.UpdateMyRoutinesByIds,
		)
		routineRoutes.POST(
			"/link-tag",
			middlewares.DelegationAuthenticatedMiddleware(
				routinesdto.LinkRoutineTagByIdOperation,
			),
			authMiddleware,
			endpoint.LinkRoutineTagById,
		)
		routineRoutes.POST(
			"/link-tags",
			middlewares.DelegationAuthenticatedMiddleware(
				routinesdto.LinkRoutineTagsByIdsOperation,
			),
			authMiddleware,
			endpoint.LinkRoutineTagsByIds,
		)
		routineRoutes.POST(
			"/link-item",
			middlewares.DelegationAuthenticatedMiddleware(
				routinesdto.LinkRoutineItemByIdOperation,
			),
			authMiddleware,
			endpoint.LinkRoutineItemById,
		)
		routineRoutes.POST(
			"/link-items",
			middlewares.DelegationAuthenticatedMiddleware(
				routinesdto.LinkRoutineItemsByIdsOperation,
			),
			authMiddleware,
			endpoint.LinkRoutineItemsByIds,
		)
		routineRoutes.POST(
			"/restore",
			middlewares.DelegationAuthenticatedMiddleware(
				routinesdto.RestoreMyRoutineByIdOperation,
			),
			authMiddleware,
			endpoint.RestoreMyRoutineById,
		)
		routineRoutes.POST(
			"/restore-many",
			middlewares.DelegationAuthenticatedMiddleware(
				routinesdto.RestoreMyRoutinesByIdsOperation,
			),
			authMiddleware,
			endpoint.RestoreMyRoutinesByIds,
		)
		routineRoutes.POST(
			"/delete",
			middlewares.DelegationAuthenticatedMiddleware(
				routinesdto.DeleteMyRoutineByIdOperation,
			),
			authMiddleware,
			endpoint.DeleteMyRoutineById,
		)
		routineRoutes.POST(
			"/delete-many",
			middlewares.DelegationAuthenticatedMiddleware(
				routinesdto.DeleteMyRoutinesByIdsOperation,
			),
			authMiddleware,
			endpoint.DeleteMyRoutinesByIds,
		)
		routineRoutes.POST(
			"/hard-delete",
			middlewares.DelegationAuthenticatedMiddleware(
				routinesdto.HardDeleteMyRoutineByIdOperation,
			),
			authMiddleware,
			endpoint.HardDeleteMyRoutineById,
		)
		routineRoutes.POST(
			"/hard-delete-many",
			middlewares.DelegationAuthenticatedMiddleware(
				routinesdto.HardDeleteMyRoutinesByIdsOperation,
			),
			authMiddleware,
			endpoint.HardDeleteMyRoutinesByIds,
		)
	}
	visualizationRoutes := router.Group("/routines/visualizations")
	{
		visualizationRoutes.POST(
			"/status-count",
			middlewares.DelegationAuthenticatedMiddleware(
				routinesdto.VisualizeMyRoutineStatusCountOperation,
			),
			authMiddleware,
			endpoint.VisualizeMyRoutineStatusCount,
		)
		visualizationRoutes.POST(
			"/period-count",
			middlewares.DelegationAuthenticatedMiddleware(
				routinesdto.VisualizeMyRoutinePeriodCountOperation,
			),
			authMiddleware,
			endpoint.VisualizeMyRoutinePeriodCount,
		)
		visualizationRoutes.POST(
			"/scheduled-start-at-count",
			middlewares.DelegationAuthenticatedMiddleware(
				routinesdto.VisualizeMyRoutineScheduledStartAtCountOperation,
			),
			authMiddleware,
			endpoint.VisualizeMyRoutineScheduledStartAtCount,
		)
		visualizationRoutes.POST(
			"/scheduled-end-at-count",
			middlewares.DelegationAuthenticatedMiddleware(
				routinesdto.VisualizeMyRoutineScheduledEndAtCountOperation,
			),
			authMiddleware,
			endpoint.VisualizeMyRoutineScheduledEndAtCount,
		)
	}
	router.POST(
		"/routines/graphql/search",
		middlewares.DelegationAuthenticatedMiddleware(
			routinesdto.SearchRoutinesOperation,
		),
		authMiddleware,
		endpoint.SearchRoutines,
	)
}
