package routers

import (
	"github.com/gin-gonic/gin"

	stationsdto "github.com/HiIamJeff67/notezy-backend/contracts/core/v1/api/stations"

	endpoints "github.com/HiIamJeff67/notezy-backend/internal/core/transports/gateway/endpoints"
	middlewares "github.com/HiIamJeff67/notezy-backend/internal/core/transports/gateway/middlewares"
)

func configureStationRoutes(
	router *gin.RouterGroup,
	authMiddleware gin.HandlerFunc,
	endpoint endpoints.StationEndpointInterface,
) {
	stationRoutes := router.Group("/stations")
	{
		stationRoutes.POST(
			"/get-by-id",
			middlewares.DelegationAuthenticatedMiddleware(
				stationsdto.GetMyStationByIdOperation,
			),
			authMiddleware,
			endpoint.GetMyStationById,
		)
		stationRoutes.POST(
			"/get-all",
			middlewares.DelegationAuthenticatedMiddleware(
				stationsdto.GetAllMyStationsOperation,
			),
			authMiddleware,
			endpoint.GetAllMyStations,
		)
		stationRoutes.POST(
			"/create",
			middlewares.DelegationAuthenticatedMiddleware(
				stationsdto.CreateStationOperation,
			),
			authMiddleware,
			endpoint.CreateStation,
		)
		stationRoutes.POST(
			"/create-many",
			middlewares.DelegationAuthenticatedMiddleware(
				stationsdto.CreateStationsOperation,
			),
			authMiddleware,
			endpoint.CreateStations,
		)
		stationRoutes.POST(
			"/update",
			middlewares.DelegationAuthenticatedMiddleware(
				stationsdto.UpdateMyStationByIdOperation,
			),
			authMiddleware,
			endpoint.UpdateMyStationById,
		)
		stationRoutes.POST(
			"/update-many",
			middlewares.DelegationAuthenticatedMiddleware(
				stationsdto.UpdateMyStationsByIdsOperation,
			),
			authMiddleware,
			endpoint.UpdateMyStationsByIds,
		)
		stationRoutes.POST(
			"/restore",
			middlewares.DelegationAuthenticatedMiddleware(
				stationsdto.RestoreMyStationByIdOperation,
			),
			authMiddleware,
			endpoint.RestoreMyStationById,
		)
		stationRoutes.POST(
			"/restore-many",
			middlewares.DelegationAuthenticatedMiddleware(
				stationsdto.RestoreMyStationsByIdsOperation,
			),
			authMiddleware,
			endpoint.RestoreMyStationsByIds,
		)
		stationRoutes.POST(
			"/delete",
			middlewares.DelegationAuthenticatedMiddleware(
				stationsdto.DeleteMyStationByIdOperation,
			),
			authMiddleware,
			endpoint.DeleteMyStationById,
		)
		stationRoutes.POST(
			"/delete-many",
			middlewares.DelegationAuthenticatedMiddleware(
				stationsdto.DeleteMyStationsByIdsOperation,
			),
			authMiddleware,
			endpoint.DeleteMyStationsByIds,
		)
		stationRoutes.POST(
			"/hard-delete",
			middlewares.DelegationAuthenticatedMiddleware(
				stationsdto.HardDeleteMyStationByIdOperation,
			),
			authMiddleware,
			endpoint.HardDeleteMyStationById,
		)
		stationRoutes.POST(
			"/hard-delete-many",
			middlewares.DelegationAuthenticatedMiddleware(
				stationsdto.HardDeleteMyStationsByIdsOperation,
			),
			authMiddleware,
			endpoint.HardDeleteMyStationsByIds,
		)
		stationRoutes.POST(
			"/visualizations/total-count",
			middlewares.DelegationAuthenticatedMiddleware(
				stationsdto.VisualizeMyTotalCountOperation,
			),
			authMiddleware,
			endpoint.VisualizeMyTotalCount,
		)
		stationRoutes.POST(
			"/permissions/get",
			middlewares.DelegationAuthenticatedMiddleware(
				stationsdto.GetMyStationPermissionOperation,
			),
			authMiddleware,
			endpoint.GetMyStationPermission,
		)
		stationRoutes.POST(
			"/permissions/create",
			middlewares.DelegationAuthenticatedMiddleware(
				stationsdto.CreateMyStationPermissionOperation,
			),
			authMiddleware,
			endpoint.CreateMyStationPermission,
		)
		stationRoutes.POST(
			"/permissions/upsert",
			middlewares.DelegationAuthenticatedMiddleware(
				stationsdto.UpsertMyStationPermissionOperation,
			),
			authMiddleware,
			endpoint.UpsertMyStationPermission,
		)
		stationRoutes.POST(
			"/permissions/upsert-many",
			middlewares.DelegationAuthenticatedMiddleware(
				stationsdto.UpsertMyStationPermissionsOperation,
			),
			authMiddleware,
			endpoint.UpsertMyStationPermissions,
		)
		stationRoutes.POST(
			"/permissions/update",
			middlewares.DelegationAuthenticatedMiddleware(
				stationsdto.UpdateMyStationPermissionOperation,
			),
			authMiddleware,
			endpoint.UpdateMyStationPermission,
		)
		stationRoutes.POST(
			"/ownership/transfer",
			middlewares.DelegationAuthenticatedMiddleware(
				stationsdto.TransferMyStationOwnershipOperation,
			),
			authMiddleware,
			endpoint.TransferMyStationOwnership,
		)
		stationRoutes.POST(
			"/permissions/delete",
			middlewares.DelegationAuthenticatedMiddleware(
				stationsdto.DeleteMyStationPermissionOperation,
			),
			authMiddleware,
			endpoint.DeleteMyStationPermission,
		)
		stationRoutes.POST(
			"/permissions/delete-many",
			middlewares.DelegationAuthenticatedMiddleware(
				stationsdto.DeleteMyStationPermissionsOperation,
			),
			authMiddleware,
			endpoint.DeleteMyStationPermissions,
		)
		stationRoutes.POST(
			"/memberships/leave",
			middlewares.DelegationAuthenticatedMiddleware(
				stationsdto.LeaveMyStationOperation,
			),
			authMiddleware,
			endpoint.LeaveMyStation,
		)
		stationRoutes.POST(
			"/memberships/leave-many",
			middlewares.DelegationAuthenticatedMiddleware(
				stationsdto.LeaveMyStationsOperation,
			),
			authMiddleware,
			endpoint.LeaveMyStations,
		)
		stationRoutes.POST(
			"/graphql/search",
			middlewares.DelegationAuthenticatedMiddleware(
				stationsdto.SearchStationsOperation,
			),
			authMiddleware,
			endpoint.SearchStations,
		)
	}
}
