package routinetaskrecordsdto

import gqlmodels "github.com/HiIamJeff67/notezy-backend/internal/platform/graphql/models"

type SearchRoutineTaskRecordsRequestDto = gqlmodels.SearchRoutineTaskRecordInput
type SearchRoutineTaskRecordsResponseDto = gqlmodels.SearchRoutineTaskRecordConnection
