FROM golang:1.26-alpine AS base

WORKDIR /notegic-backend

RUN apk add --no-cache git

COPY contracts/go.mod contracts/go.sum contracts/
COPY shared/go.mod shared/go.sum shared/
COPY internal/clientgateway/go.mod internal/clientgateway/go.sum internal/clientgateway/
WORKDIR /notegic-backend/internal/clientgateway
RUN go mod download
WORKDIR /notegic-backend

COPY . .

FROM base AS dev

WORKDIR /notegic-backend/internal/clientgateway

RUN go install github.com/air-verse/air@latest

FROM base AS builder

WORKDIR /notegic-backend/internal/clientgateway

RUN CGO_ENABLED=0 GOOS=linux go build -o /out/clientgateway ./commands

FROM alpine:latest AS production

WORKDIR /app

RUN apk --no-cache add ca-certificates

COPY --from=builder /out/clientgateway /app/clientgateway

EXPOSE 7777

CMD ["/app/clientgateway"]
