// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlmodels

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/HiIamJeff67/notezy-backend/app/models/schemas/enums"
	"github.com/google/uuid"
	"gorm.io/datatypes"
)

type SearchConnection interface {
	IsSearchConnection()
	GetSearchPageInfo() *SearchPageInfo
	GetTotalCount() int32
	GetSearchTime() float64
}

type SearchEdge interface {
	IsSearchEdge()
	GetEncodedSearchCursor() string
}

type PrivateBlock struct {
	ID            uuid.UUID       `json:"id"`
	ParentBlockID *uuid.UUID      `json:"parentBlockId,omitempty"`
	BlockGroupID  uuid.UUID       `json:"blockGroupId"`
	Type          enums.BlockType `json:"type"`
	Props         datatypes.JSON  `json:"props"`
	Content       datatypes.JSON  `json:"content"`
	DeletedAt     *time.Time      `json:"deletedAt,omitempty"`
	UpdatedAt     time.Time       `json:"updatedAt"`
	CreatedAt     time.Time       `json:"createdAt"`
	ChildrenIds   []uuid.UUID     `json:"childrenIds"`
}

type PrivateItem struct {
	ID               uuid.UUID         `json:"id"`
	ParentSubShelfID uuid.UUID         `json:"parentSubShelfId"`
	RootShelfID      uuid.UUID         `json:"rootShelfId"`
	Type             enums.ItemType    `json:"type"`
	DeletedAt        *time.Time        `json:"deletedAt,omitempty"`
	UpdatedAt        time.Time         `json:"updatedAt"`
	CreatedAt        time.Time         `json:"createdAt"`
	ParentSubShelf   *PrivateSubShelf  `json:"parentSubShelf"`
	RootShelf        *PrivateRootShelf `json:"rootShelf"`
	Routines         []*PrivateRoutine `json:"routines"`
}

type PrivateMaterial struct {
	ID               uuid.UUID                 `json:"id"`
	ParentSubShelfID uuid.UUID                 `json:"parentSubShelfId"`
	Name             string                    `json:"name"`
	Size             float64                   `json:"size"`
	ContentKey       string                    `json:"contentKey"`
	ContentType      enums.MaterialContentType `json:"contentType"`
	ParseMediaType   string                    `json:"parseMediaType"`
	DeletedAt        *time.Time                `json:"deletedAt,omitempty"`
	UpdatedAt        time.Time                 `json:"updatedAt"`
	CreatedAt        time.Time                 `json:"createdAt"`
	ParentSubShelf   *PrivateSubShelf          `json:"parentSubShelf"`
}

type PrivateRootShelf struct {
	ID             uuid.UUID                     `json:"id"`
	Name           string                        `json:"name"`
	Permission     enums.AccessControlPermission `json:"permission"`
	SubShelfCount  int64                         `json:"subShelfCount"`
	ItemCount      int64                         `json:"itemCount"`
	LastAnalyzedAt time.Time                     `json:"lastAnalyzedAt"`
	DeletedAt      *time.Time                    `json:"deletedAt,omitempty"`
	UpdatedAt      time.Time                     `json:"updatedAt"`
	CreatedAt      time.Time                     `json:"createdAt"`
	Owner          *PublicUser                   `json:"owner"`
	Sharers        []*PublicUser                 `json:"sharers"`
	Items          []*PrivateItem                `json:"items"`
}

type PrivateRoutine struct {
	ID               uuid.UUID            `json:"id"`
	StationID        uuid.UUID            `json:"stationId"`
	Title            string               `json:"title"`
	Description      string               `json:"description"`
	Status           enums.RoutineStatus  `json:"status"`
	IsPinned         bool                 `json:"isPinned"`
	ScheduledStartAt time.Time            `json:"scheduledStartAt"`
	ScheduledEndAt   time.Time            `json:"scheduledEndAt"`
	Period           *enums.RoutinePeriod `json:"period,omitempty"`
	Timezone         string               `json:"timezone"`
	DeletedAt        *time.Time           `json:"deletedAt,omitempty"`
	UpdatedAt        time.Time            `json:"updatedAt"`
	CreatedAt        time.Time            `json:"createdAt"`
	TagIds           []uuid.UUID          `json:"tagIds"`
	TaskIds          []uuid.UUID          `json:"taskIds"`
	ItemIds          []uuid.UUID          `json:"itemIds"`
}

type PrivateRoutineTag struct {
	ID        uuid.UUID            `json:"id"`
	Name      string               `json:"name"`
	Color     string               `json:"color"`
	Icon      *enums.SupportedIcon `json:"icon,omitempty"`
	UpdatedAt time.Time            `json:"updatedAt"`
	CreatedAt time.Time            `json:"createdAt"`
}

type PrivateRoutineTask struct {
	ID              uuid.UUID                `json:"id"`
	StationID       uuid.UUID                `json:"stationId"`
	Title           string                   `json:"title"`
	Purpose         enums.RoutineTaskPurpose `json:"purpose"`
	Payload         json.RawMessage          `json:"payload"`
	CostUnit        int64                    `json:"costUnit"`
	Priority        int32                    `json:"priority"`
	Status          enums.RoutineTaskStatus  `json:"status"`
	Attempts        int32                    `json:"attempts"`
	MaxAttempts     int32                    `json:"maxAttempts"`
	Period          *enums.RoutinePeriod     `json:"period,omitempty"`
	ScheduledAt     time.Time                `json:"scheduledAt"`
	ActualStartedAt *time.Time               `json:"actualStartedAt,omitempty"`
	ActualEndedAt   *time.Time               `json:"actualEndedAt,omitempty"`
	UpdatedAt       time.Time                `json:"updatedAt"`
	CreatedAt       time.Time                `json:"createdAt"`
}

type PrivateSearchableRoutine struct {
	ID               uuid.UUID            `json:"id"`
	StationID        uuid.UUID            `json:"stationId"`
	Title            string               `json:"title"`
	Status           enums.RoutineStatus  `json:"status"`
	IsPinned         bool                 `json:"isPinned"`
	ScheduledStartAt time.Time            `json:"scheduledStartAt"`
	ScheduledEndAt   time.Time            `json:"scheduledEndAt"`
	Period           *enums.RoutinePeriod `json:"period,omitempty"`
	Timezone         string               `json:"timezone"`
	DeletedAt        *time.Time           `json:"deletedAt,omitempty"`
	UpdatedAt        time.Time            `json:"updatedAt"`
	CreatedAt        time.Time            `json:"createdAt"`
	TagIds           []uuid.UUID          `json:"tagIds"`
	TaskIds          []uuid.UUID          `json:"taskIds"`
	ItemIds          []uuid.UUID          `json:"itemIds"`
}

type PrivateSearchableStation struct {
	ID                  uuid.UUID                     `json:"id"`
	Permission          enums.AccessControlPermission `json:"permission"`
	Name                string                        `json:"name"`
	Icon                *enums.SupportedIcon          `json:"icon,omitempty"`
	HeaderBackgroundURL *string                       `json:"headerBackgroundURL,omitempty"`
	RoutineCount        int64                         `json:"routineCount"`
	RoutineTaskCount    int64                         `json:"routineTaskCount"`
	DeletedAt           *time.Time                    `json:"deletedAt,omitempty"`
	CreatedAt           time.Time                     `json:"createdAt"`
	UpdatedAt           time.Time                     `json:"updatedAt"`
}

type PrivateStation struct {
	ID                  uuid.UUID                     `json:"id"`
	Permission          enums.AccessControlPermission `json:"permission"`
	Name                string                        `json:"name"`
	Description         string                        `json:"description"`
	Icon                *enums.SupportedIcon          `json:"icon,omitempty"`
	HeaderBackgroundURL *string                       `json:"headerBackgroundURL,omitempty"`
	RoutineCount        int64                         `json:"routineCount"`
	RoutineTaskCount    int64                         `json:"routineTaskCount"`
	DeletedAt           *time.Time                    `json:"deletedAt,omitempty"`
	CreatedAt           time.Time                     `json:"createdAt"`
	UpdatedAt           time.Time                     `json:"updatedAt"`
}

type PrivateSubShelf struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	RootShelfID    uuid.UUID          `json:"rootShelfId"`
	PrevSubShelfID *uuid.UUID         `json:"prevSubShelfId,omitempty"`
	Path           []uuid.UUID        `json:"path"`
	DeletedAt      *time.Time         `json:"deletedAt,omitempty"`
	UpdatedAt      time.Time          `json:"updatedAt"`
	CreatedAt      time.Time          `json:"createdAt"`
	RootShelf      *PrivateRootShelf  `json:"rootShelf"`
	NextSubShelves []*PrivateSubShelf `json:"nextSubShelves"`
	Materials      []*PrivateMaterial `json:"materials"`
	Items          []*PrivateItem     `json:"items"`
}

type PublicBadge struct {
	PublicID    string          `json:"publicId"`
	Title       string          `json:"title"`
	Description string          `json:"description"`
	Type        enums.BadgeType `json:"type"`
	ImageURL    *string         `json:"imageURL,omitempty"`
	CreatedAt   time.Time       `json:"createdAt"`
	Users       []*PublicUser   `json:"users"`
}

type PublicTheme struct {
	PublicID      string      `json:"publicId"`
	Name          string      `json:"name"`
	IsDark        bool        `json:"isDark"`
	Version       string      `json:"version"`
	IsDefault     bool        `json:"isDefault"`
	DownloadURL   *string     `json:"downloadURL,omitempty"`
	DownloadCount int64       `json:"downloadCount"`
	CreatedAt     time.Time   `json:"createdAt"`
	UpdatedAt     time.Time   `json:"updatedAt"`
	Author        *PublicUser `json:"author"`
}

type PublicUser struct {
	PublicID    string           `json:"publicId"`
	Name        string           `json:"name"`
	DisplayName string           `json:"displayName"`
	Role        enums.UserRole   `json:"role"`
	Plan        enums.UserPlan   `json:"plan"`
	Status      enums.UserStatus `json:"status"`
	CreatedAt   time.Time        `json:"createdAt"`
	UserInfo    *PublicUserInfo  `json:"userInfo"`
	Badges      []*PublicBadge   `json:"badges"`
	Themes      []*PublicTheme   `json:"themes"`
}

type PublicUserInfo struct {
	AvatarURL          *string          `json:"avatarURL,omitempty"`
	CoverBackgroundURL *string          `json:"coverBackgroundURL,omitempty"`
	Header             *string          `json:"header,omitempty"`
	Introduction       *string          `json:"introduction,omitempty"`
	Gender             enums.UserGender `json:"gender"`
	Country            *enums.Country   `json:"country,omitempty"`
	BirthDate          time.Time        `json:"birthDate"`
}

type Query struct {
}

type SearchBadgeConnection struct {
	SearchEdges    []*SearchBadgeEdge `json:"searchEdges"`
	SearchPageInfo *SearchPageInfo    `json:"searchPageInfo"`
	TotalCount     int32              `json:"totalCount"`
	SearchTime     float64            `json:"searchTime"`
}

func (SearchBadgeConnection) IsSearchConnection()                     {}
func (this SearchBadgeConnection) GetSearchPageInfo() *SearchPageInfo { return this.SearchPageInfo }
func (this SearchBadgeConnection) GetTotalCount() int32               { return this.TotalCount }
func (this SearchBadgeConnection) GetSearchTime() float64             { return this.SearchTime }

type SearchBadgeCursorFields struct {
	PublicID string `json:"publicId"`
}

type SearchBadgeEdge struct {
	EncodedSearchCursor string       `json:"encodedSearchCursor"`
	Node                *PublicBadge `json:"node"`
}

func (SearchBadgeEdge) IsSearchEdge()                       {}
func (this SearchBadgeEdge) GetEncodedSearchCursor() string { return this.EncodedSearchCursor }

type SearchBadgeFilters struct {
	Type *enums.BadgeType `json:"type,omitempty"`
}

type SearchBadgeInput struct {
	Query     string              `json:"query"`
	After     *string             `json:"after,omitempty"`
	First     *int32              `json:"first,omitempty"`
	Filters   *SearchBadgeFilters `json:"filters,omitempty"`
	SortBy    *SearchBadgeSortBy  `json:"sortBy,omitempty"`
	SortOrder *SearchSortOrder    `json:"sortOrder,omitempty"`
}

type SearchBlockConnection struct {
	SearchEdges    []*SearchBlockEdge `json:"searchEdges"`
	SearchPageInfo *SearchPageInfo    `json:"searchPageInfo"`
	TotalCount     int32              `json:"totalCount"`
	SearchTime     float64            `json:"searchTime"`
}

func (SearchBlockConnection) IsSearchConnection()                     {}
func (this SearchBlockConnection) GetSearchPageInfo() *SearchPageInfo { return this.SearchPageInfo }
func (this SearchBlockConnection) GetTotalCount() int32               { return this.TotalCount }
func (this SearchBlockConnection) GetSearchTime() float64             { return this.SearchTime }

type SearchBlockCursorFields struct {
	ID uuid.UUID `json:"id"`
}

type SearchBlockEdge struct {
	EncodedSearchCursor string        `json:"encodedSearchCursor"`
	Node                *PrivateBlock `json:"node"`
}

func (SearchBlockEdge) IsSearchEdge()                       {}
func (this SearchBlockEdge) GetEncodedSearchCursor() string { return this.EncodedSearchCursor }

type SearchBlockInput struct {
	Query     string             `json:"query"`
	After     *string            `json:"after,omitempty"`
	First     *int32             `json:"first,omitempty"`
	SortBy    *SearchBlockSortBy `json:"sortBy,omitempty"`
	SortOrder *SearchSortOrder   `json:"sortOrder,omitempty"`
}

type SearchItemConnection struct {
	SearchEdges    []*SearchItemEdge `json:"searchEdges"`
	SearchPageInfo *SearchPageInfo   `json:"searchPageInfo"`
	TotalCount     int32             `json:"totalCount"`
	SearchTime     float64           `json:"searchTime"`
}

func (SearchItemConnection) IsSearchConnection()                     {}
func (this SearchItemConnection) GetSearchPageInfo() *SearchPageInfo { return this.SearchPageInfo }
func (this SearchItemConnection) GetTotalCount() int32               { return this.TotalCount }
func (this SearchItemConnection) GetSearchTime() float64             { return this.SearchTime }

type SearchItemCursorFields struct {
	ID uuid.UUID `json:"id"`
}

type SearchItemEdge struct {
	EncodedSearchCursor string       `json:"encodedSearchCursor"`
	Node                *PrivateItem `json:"node"`
}

func (SearchItemEdge) IsSearchEdge()                       {}
func (this SearchItemEdge) GetEncodedSearchCursor() string { return this.EncodedSearchCursor }

type SearchItemInput struct {
	ParentSubShelfID *uuid.UUID        `json:"parentSubShelfId,omitempty"`
	RootShelfID      *uuid.UUID        `json:"rootShelfId,omitempty"`
	Query            string            `json:"query"`
	After            *string           `json:"after,omitempty"`
	First            *int32            `json:"first,omitempty"`
	SortBy           *SearchItemSortBy `json:"sortBy,omitempty"`
	SortOrder        *SearchSortOrder  `json:"sortOrder,omitempty"`
}

type SearchPageInfo struct {
	HasNextPage              bool    `json:"hasNextPage"`
	HasPreviousPage          bool    `json:"hasPreviousPage"`
	StartEncodedSearchCursor *string `json:"startEncodedSearchCursor,omitempty"`
	EndEncodedSearchCursor   *string `json:"endEncodedSearchCursor,omitempty"`
}

type SearchRootShelfConnection struct {
	SearchEdges    []*SearchRootShelfEdge `json:"searchEdges"`
	SearchPageInfo *SearchPageInfo        `json:"searchPageInfo"`
	TotalCount     int32                  `json:"totalCount"`
	SearchTime     float64                `json:"searchTime"`
}

func (SearchRootShelfConnection) IsSearchConnection()                     {}
func (this SearchRootShelfConnection) GetSearchPageInfo() *SearchPageInfo { return this.SearchPageInfo }
func (this SearchRootShelfConnection) GetTotalCount() int32               { return this.TotalCount }
func (this SearchRootShelfConnection) GetSearchTime() float64             { return this.SearchTime }

type SearchRootShelfCursorFields struct {
	ID uuid.UUID `json:"id"`
}

type SearchRootShelfEdge struct {
	EncodedSearchCursor string            `json:"encodedSearchCursor"`
	Node                *PrivateRootShelf `json:"node"`
}

func (SearchRootShelfEdge) IsSearchEdge()                       {}
func (this SearchRootShelfEdge) GetEncodedSearchCursor() string { return this.EncodedSearchCursor }

type SearchRootShelfInput struct {
	Query     string                 `json:"query"`
	After     *string                `json:"after,omitempty"`
	First     *int32                 `json:"first,omitempty"`
	SortBy    *SearchRootShelfSortBy `json:"sortBy,omitempty"`
	SortOrder *SearchSortOrder       `json:"sortOrder,omitempty"`
}

type SearchRoutineConnection struct {
	SearchEdges    []*SearchRoutineEdge `json:"searchEdges"`
	SearchPageInfo *SearchPageInfo      `json:"searchPageInfo"`
	TotalCount     int32                `json:"totalCount"`
	SearchTime     float64              `json:"searchTime"`
}

func (SearchRoutineConnection) IsSearchConnection()                     {}
func (this SearchRoutineConnection) GetSearchPageInfo() *SearchPageInfo { return this.SearchPageInfo }
func (this SearchRoutineConnection) GetTotalCount() int32               { return this.TotalCount }
func (this SearchRoutineConnection) GetSearchTime() float64             { return this.SearchTime }

type SearchRoutineCursorFields struct {
	ID uuid.UUID `json:"id"`
}

type SearchRoutineEdge struct {
	EncodedSearchCursor string                    `json:"encodedSearchCursor"`
	Node                *PrivateSearchableRoutine `json:"node"`
}

func (SearchRoutineEdge) IsSearchEdge()                       {}
func (this SearchRoutineEdge) GetEncodedSearchCursor() string { return this.EncodedSearchCursor }

type SearchRoutineInput struct {
	StationIds []uuid.UUID          `json:"stationIds"`
	TagIds     []uuid.UUID          `json:"tagIds"`
	Query      string               `json:"query"`
	After      *string              `json:"after,omitempty"`
	First      *int32               `json:"first,omitempty"`
	SortBy     *SearchRoutineSortBy `json:"sortBy,omitempty"`
	SortOrder  *SearchSortOrder     `json:"sortOrder,omitempty"`
}

type SearchRoutineTagConnection struct {
	SearchEdges    []*SearchRoutineTagEdge `json:"searchEdges"`
	SearchPageInfo *SearchPageInfo         `json:"searchPageInfo"`
	TotalCount     int32                   `json:"totalCount"`
	SearchTime     float64                 `json:"searchTime"`
}

func (SearchRoutineTagConnection) IsSearchConnection() {}
func (this SearchRoutineTagConnection) GetSearchPageInfo() *SearchPageInfo {
	return this.SearchPageInfo
}
func (this SearchRoutineTagConnection) GetTotalCount() int32   { return this.TotalCount }
func (this SearchRoutineTagConnection) GetSearchTime() float64 { return this.SearchTime }

type SearchRoutineTagCursorFields struct {
	ID uuid.UUID `json:"id"`
}

type SearchRoutineTagEdge struct {
	EncodedSearchCursor string             `json:"encodedSearchCursor"`
	Node                *PrivateRoutineTag `json:"node"`
}

func (SearchRoutineTagEdge) IsSearchEdge()                       {}
func (this SearchRoutineTagEdge) GetEncodedSearchCursor() string { return this.EncodedSearchCursor }

type SearchRoutineTagInput struct {
	Query     string                  `json:"query"`
	After     *string                 `json:"after,omitempty"`
	First     *int32                  `json:"first,omitempty"`
	SortBy    *SearchRoutineTagSortBy `json:"sortBy,omitempty"`
	SortOrder *SearchSortOrder        `json:"sortOrder,omitempty"`
}

type SearchRoutineTaskConnection struct {
	SearchEdges    []*SearchRoutineTaskEdge `json:"searchEdges"`
	SearchPageInfo *SearchPageInfo          `json:"searchPageInfo"`
	TotalCount     int32                    `json:"totalCount"`
	SearchTime     float64                  `json:"searchTime"`
}

func (SearchRoutineTaskConnection) IsSearchConnection() {}
func (this SearchRoutineTaskConnection) GetSearchPageInfo() *SearchPageInfo {
	return this.SearchPageInfo
}
func (this SearchRoutineTaskConnection) GetTotalCount() int32   { return this.TotalCount }
func (this SearchRoutineTaskConnection) GetSearchTime() float64 { return this.SearchTime }

type SearchRoutineTaskCursorFields struct {
	ID uuid.UUID `json:"id"`
}

type SearchRoutineTaskEdge struct {
	EncodedSearchCursor string              `json:"encodedSearchCursor"`
	Node                *PrivateRoutineTask `json:"node"`
}

func (SearchRoutineTaskEdge) IsSearchEdge()                       {}
func (this SearchRoutineTaskEdge) GetEncodedSearchCursor() string { return this.EncodedSearchCursor }

type SearchRoutineTaskInput struct {
	StationID *uuid.UUID               `json:"stationId,omitempty"`
	Query     string                   `json:"query"`
	After     *string                  `json:"after,omitempty"`
	First     *int32                   `json:"first,omitempty"`
	SortBy    *SearchRoutineTaskSortBy `json:"sortBy,omitempty"`
	SortOrder *SearchSortOrder         `json:"sortOrder,omitempty"`
}

type SearchStationConnection struct {
	SearchEdges    []*SearchStationEdge `json:"searchEdges"`
	SearchPageInfo *SearchPageInfo      `json:"searchPageInfo"`
	TotalCount     int32                `json:"totalCount"`
	SearchTime     float64              `json:"searchTime"`
}

func (SearchStationConnection) IsSearchConnection()                     {}
func (this SearchStationConnection) GetSearchPageInfo() *SearchPageInfo { return this.SearchPageInfo }
func (this SearchStationConnection) GetTotalCount() int32               { return this.TotalCount }
func (this SearchStationConnection) GetSearchTime() float64             { return this.SearchTime }

type SearchStationCursorFields struct {
	ID uuid.UUID `json:"id"`
}

type SearchStationEdge struct {
	EncodedSearchCursor string                    `json:"encodedSearchCursor"`
	Node                *PrivateSearchableStation `json:"node"`
}

func (SearchStationEdge) IsSearchEdge()                       {}
func (this SearchStationEdge) GetEncodedSearchCursor() string { return this.EncodedSearchCursor }

type SearchStationInput struct {
	Query     string               `json:"query"`
	After     *string              `json:"after,omitempty"`
	First     *int32               `json:"first,omitempty"`
	SortBy    *SearchStationSortBy `json:"sortBy,omitempty"`
	SortOrder *SearchSortOrder     `json:"sortOrder,omitempty"`
}

type SearchThemeConnection struct {
	SearchEdges    []*SearchThemeEdge `json:"searchEdges"`
	SearchPageInfo *SearchPageInfo    `json:"searchPageInfo"`
	TotalCount     int32              `json:"totalCount"`
	SearchTime     float64            `json:"searchTime"`
}

func (SearchThemeConnection) IsSearchConnection()                     {}
func (this SearchThemeConnection) GetSearchPageInfo() *SearchPageInfo { return this.SearchPageInfo }
func (this SearchThemeConnection) GetTotalCount() int32               { return this.TotalCount }
func (this SearchThemeConnection) GetSearchTime() float64             { return this.SearchTime }

type SearchThemeCursorFields struct {
	PublicID string `json:"publicId"`
}

type SearchThemeEdge struct {
	EncodedSearchCursor string       `json:"encodedSearchCursor"`
	Node                *PublicTheme `json:"node"`
}

func (SearchThemeEdge) IsSearchEdge()                       {}
func (this SearchThemeEdge) GetEncodedSearchCursor() string { return this.EncodedSearchCursor }

type SearchThemeFilters struct {
	IsDefault                *bool  `json:"isDefault,omitempty"`
	DownloadCountGreaterThan *int32 `json:"downloadCountGreaterThan,omitempty"`
}

type SearchThemeInput struct {
	Query     string              `json:"query"`
	After     *string             `json:"after,omitempty"`
	First     *int32              `json:"first,omitempty"`
	Filters   *SearchThemeFilters `json:"filters,omitempty"`
	SortBy    *SearchThemeSortBy  `json:"sortBy,omitempty"`
	SortOrder *SearchSortOrder    `json:"sortOrder,omitempty"`
}

type SearchUserConnection struct {
	SearchEdges    []*SearchUserEdge `json:"searchEdges"`
	SearchPageInfo *SearchPageInfo   `json:"searchPageInfo"`
	TotalCount     int32             `json:"totalCount"`
	SearchTime     float64           `json:"searchTime"`
}

func (SearchUserConnection) IsSearchConnection()                     {}
func (this SearchUserConnection) GetSearchPageInfo() *SearchPageInfo { return this.SearchPageInfo }
func (this SearchUserConnection) GetTotalCount() int32               { return this.TotalCount }
func (this SearchUserConnection) GetSearchTime() float64             { return this.SearchTime }

type SearchUserCursorFields struct {
	PublicID string `json:"publicId"`
}

type SearchUserEdge struct {
	EncodedSearchCursor string      `json:"encodedSearchCursor"`
	Node                *PublicUser `json:"node"`
}

func (SearchUserEdge) IsSearchEdge()                       {}
func (this SearchUserEdge) GetEncodedSearchCursor() string { return this.EncodedSearchCursor }

type SearchUserFilters struct {
	Role      *enums.UserRole   `json:"role,omitempty"`
	Plan      *enums.UserPlan   `json:"plan,omitempty"`
	Status    *enums.UserStatus `json:"status,omitempty"`
	HasAvatar *bool             `json:"hasAvatar,omitempty"`
	Country   *enums.Country    `json:"country,omitempty"`
	IsOnline  *bool             `json:"isOnline,omitempty"`
}

type SearchUserInput struct {
	Query     string             `json:"query"`
	After     *string            `json:"after,omitempty"`
	First     *int32             `json:"first,omitempty"`
	Filters   *SearchUserFilters `json:"filters,omitempty"`
	SortBy    *SearchUserSortBy  `json:"sortBy,omitempty"`
	SortOrder *SearchSortOrder   `json:"sortOrder,omitempty"`
}

type SearchBadgeSortBy string

const (
	SearchBadgeSortByRelevance SearchBadgeSortBy = "RELEVANCE"
	SearchBadgeSortByTitle     SearchBadgeSortBy = "TITLE"
	SearchBadgeSortByCreatedAt SearchBadgeSortBy = "CREATED_AT"
)

var AllSearchBadgeSortBy = []SearchBadgeSortBy{
	SearchBadgeSortByRelevance,
	SearchBadgeSortByTitle,
	SearchBadgeSortByCreatedAt,
}

func (e SearchBadgeSortBy) IsValid() bool {
	switch e {
	case SearchBadgeSortByRelevance, SearchBadgeSortByTitle, SearchBadgeSortByCreatedAt:
		return true
	}
	return false
}

func (e SearchBadgeSortBy) String() string {
	return string(e)
}

func (e *SearchBadgeSortBy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SearchBadgeSortBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SearchBadgeSortBy", str)
	}
	return nil
}

func (e SearchBadgeSortBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SearchBadgeSortBy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SearchBadgeSortBy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SearchBlockSortBy string

const (
	SearchBlockSortByRelevance  SearchBlockSortBy = "RELEVANCE"
	SearchBlockSortByType       SearchBlockSortBy = "TYPE"
	SearchBlockSortByLastUpdate SearchBlockSortBy = "LAST_UPDATE"
	SearchBlockSortByCreatedAt  SearchBlockSortBy = "CREATED_AT"
)

var AllSearchBlockSortBy = []SearchBlockSortBy{
	SearchBlockSortByRelevance,
	SearchBlockSortByType,
	SearchBlockSortByLastUpdate,
	SearchBlockSortByCreatedAt,
}

func (e SearchBlockSortBy) IsValid() bool {
	switch e {
	case SearchBlockSortByRelevance, SearchBlockSortByType, SearchBlockSortByLastUpdate, SearchBlockSortByCreatedAt:
		return true
	}
	return false
}

func (e SearchBlockSortBy) String() string {
	return string(e)
}

func (e *SearchBlockSortBy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SearchBlockSortBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SearchBlockSortBy", str)
	}
	return nil
}

func (e SearchBlockSortBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SearchBlockSortBy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SearchBlockSortBy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SearchItemSortBy string

const (
	SearchItemSortByRelevance  SearchItemSortBy = "RELEVANCE"
	SearchItemSortByType       SearchItemSortBy = "TYPE"
	SearchItemSortByLastUpdate SearchItemSortBy = "LAST_UPDATE"
	SearchItemSortByCreatedAt  SearchItemSortBy = "CREATED_AT"
)

var AllSearchItemSortBy = []SearchItemSortBy{
	SearchItemSortByRelevance,
	SearchItemSortByType,
	SearchItemSortByLastUpdate,
	SearchItemSortByCreatedAt,
}

func (e SearchItemSortBy) IsValid() bool {
	switch e {
	case SearchItemSortByRelevance, SearchItemSortByType, SearchItemSortByLastUpdate, SearchItemSortByCreatedAt:
		return true
	}
	return false
}

func (e SearchItemSortBy) String() string {
	return string(e)
}

func (e *SearchItemSortBy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SearchItemSortBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SearchItemSortBy", str)
	}
	return nil
}

func (e SearchItemSortBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SearchItemSortBy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SearchItemSortBy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SearchRootShelfSortBy string

const (
	SearchRootShelfSortByRelevance  SearchRootShelfSortBy = "RELEVANCE"
	SearchRootShelfSortByName       SearchRootShelfSortBy = "NAME"
	SearchRootShelfSortByLastUpdate SearchRootShelfSortBy = "LAST_UPDATE"
	SearchRootShelfSortByCreatedAt  SearchRootShelfSortBy = "CREATED_AT"
)

var AllSearchRootShelfSortBy = []SearchRootShelfSortBy{
	SearchRootShelfSortByRelevance,
	SearchRootShelfSortByName,
	SearchRootShelfSortByLastUpdate,
	SearchRootShelfSortByCreatedAt,
}

func (e SearchRootShelfSortBy) IsValid() bool {
	switch e {
	case SearchRootShelfSortByRelevance, SearchRootShelfSortByName, SearchRootShelfSortByLastUpdate, SearchRootShelfSortByCreatedAt:
		return true
	}
	return false
}

func (e SearchRootShelfSortBy) String() string {
	return string(e)
}

func (e *SearchRootShelfSortBy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SearchRootShelfSortBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SearchRootShelfSortBy", str)
	}
	return nil
}

func (e SearchRootShelfSortBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SearchRootShelfSortBy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SearchRootShelfSortBy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SearchRoutineSortBy string

const (
	SearchRoutineSortByRelevance        SearchRoutineSortBy = "RELEVANCE"
	SearchRoutineSortByTitle            SearchRoutineSortBy = "TITLE"
	SearchRoutineSortByStatus           SearchRoutineSortBy = "STATUS"
	SearchRoutineSortByScheduledStartAt SearchRoutineSortBy = "SCHEDULED_START_AT"
	SearchRoutineSortByScheduledEndAt   SearchRoutineSortBy = "SCHEDULED_END_AT"
	SearchRoutineSortByPeriod           SearchRoutineSortBy = "PERIOD"
	SearchRoutineSortByLastUpdate       SearchRoutineSortBy = "LAST_UPDATE"
	SearchRoutineSortByCreatedAt        SearchRoutineSortBy = "CREATED_AT"
)

var AllSearchRoutineSortBy = []SearchRoutineSortBy{
	SearchRoutineSortByRelevance,
	SearchRoutineSortByTitle,
	SearchRoutineSortByStatus,
	SearchRoutineSortByScheduledStartAt,
	SearchRoutineSortByScheduledEndAt,
	SearchRoutineSortByPeriod,
	SearchRoutineSortByLastUpdate,
	SearchRoutineSortByCreatedAt,
}

func (e SearchRoutineSortBy) IsValid() bool {
	switch e {
	case SearchRoutineSortByRelevance, SearchRoutineSortByTitle, SearchRoutineSortByStatus, SearchRoutineSortByScheduledStartAt, SearchRoutineSortByScheduledEndAt, SearchRoutineSortByPeriod, SearchRoutineSortByLastUpdate, SearchRoutineSortByCreatedAt:
		return true
	}
	return false
}

func (e SearchRoutineSortBy) String() string {
	return string(e)
}

func (e *SearchRoutineSortBy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SearchRoutineSortBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SearchRoutineSortBy", str)
	}
	return nil
}

func (e SearchRoutineSortBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SearchRoutineSortBy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SearchRoutineSortBy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SearchRoutineTagSortBy string

const (
	SearchRoutineTagSortByRelevance  SearchRoutineTagSortBy = "RELEVANCE"
	SearchRoutineTagSortByName       SearchRoutineTagSortBy = "NAME"
	SearchRoutineTagSortByLastUpdate SearchRoutineTagSortBy = "LAST_UPDATE"
	SearchRoutineTagSortByCreatedAt  SearchRoutineTagSortBy = "CREATED_AT"
)

var AllSearchRoutineTagSortBy = []SearchRoutineTagSortBy{
	SearchRoutineTagSortByRelevance,
	SearchRoutineTagSortByName,
	SearchRoutineTagSortByLastUpdate,
	SearchRoutineTagSortByCreatedAt,
}

func (e SearchRoutineTagSortBy) IsValid() bool {
	switch e {
	case SearchRoutineTagSortByRelevance, SearchRoutineTagSortByName, SearchRoutineTagSortByLastUpdate, SearchRoutineTagSortByCreatedAt:
		return true
	}
	return false
}

func (e SearchRoutineTagSortBy) String() string {
	return string(e)
}

func (e *SearchRoutineTagSortBy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SearchRoutineTagSortBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SearchRoutineTagSortBy", str)
	}
	return nil
}

func (e SearchRoutineTagSortBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SearchRoutineTagSortBy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SearchRoutineTagSortBy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SearchRoutineTaskSortBy string

const (
	SearchRoutineTaskSortByRelevance       SearchRoutineTaskSortBy = "RELEVANCE"
	SearchRoutineTaskSortByTitle           SearchRoutineTaskSortBy = "TITLE"
	SearchRoutineTaskSortByPurpose         SearchRoutineTaskSortBy = "PURPOSE"
	SearchRoutineTaskSortByPriority        SearchRoutineTaskSortBy = "PRIORITY"
	SearchRoutineTaskSortByStatus          SearchRoutineTaskSortBy = "STATUS"
	SearchRoutineTaskSortByAttempts        SearchRoutineTaskSortBy = "ATTEMPTS"
	SearchRoutineTaskSortByMaxAttempts     SearchRoutineTaskSortBy = "MAX_ATTEMPTS"
	SearchRoutineTaskSortByScheduledAt     SearchRoutineTaskSortBy = "SCHEDULED_AT"
	SearchRoutineTaskSortByActualStartedAt SearchRoutineTaskSortBy = "ACTUAL_STARTED_AT"
	SearchRoutineTaskSortByActualEndedAt   SearchRoutineTaskSortBy = "ACTUAL_ENDED_AT"
	SearchRoutineTaskSortByLastUpdate      SearchRoutineTaskSortBy = "LAST_UPDATE"
	SearchRoutineTaskSortByCreatedAt       SearchRoutineTaskSortBy = "CREATED_AT"
)

var AllSearchRoutineTaskSortBy = []SearchRoutineTaskSortBy{
	SearchRoutineTaskSortByRelevance,
	SearchRoutineTaskSortByTitle,
	SearchRoutineTaskSortByPurpose,
	SearchRoutineTaskSortByPriority,
	SearchRoutineTaskSortByStatus,
	SearchRoutineTaskSortByAttempts,
	SearchRoutineTaskSortByMaxAttempts,
	SearchRoutineTaskSortByScheduledAt,
	SearchRoutineTaskSortByActualStartedAt,
	SearchRoutineTaskSortByActualEndedAt,
	SearchRoutineTaskSortByLastUpdate,
	SearchRoutineTaskSortByCreatedAt,
}

func (e SearchRoutineTaskSortBy) IsValid() bool {
	switch e {
	case SearchRoutineTaskSortByRelevance, SearchRoutineTaskSortByTitle, SearchRoutineTaskSortByPurpose, SearchRoutineTaskSortByPriority, SearchRoutineTaskSortByStatus, SearchRoutineTaskSortByAttempts, SearchRoutineTaskSortByMaxAttempts, SearchRoutineTaskSortByScheduledAt, SearchRoutineTaskSortByActualStartedAt, SearchRoutineTaskSortByActualEndedAt, SearchRoutineTaskSortByLastUpdate, SearchRoutineTaskSortByCreatedAt:
		return true
	}
	return false
}

func (e SearchRoutineTaskSortBy) String() string {
	return string(e)
}

func (e *SearchRoutineTaskSortBy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SearchRoutineTaskSortBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SearchRoutineTaskSortBy", str)
	}
	return nil
}

func (e SearchRoutineTaskSortBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SearchRoutineTaskSortBy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SearchRoutineTaskSortBy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SearchSortOrder string

const (
	SearchSortOrderAsc  SearchSortOrder = "ASC"
	SearchSortOrderDesc SearchSortOrder = "DESC"
)

var AllSearchSortOrder = []SearchSortOrder{
	SearchSortOrderAsc,
	SearchSortOrderDesc,
}

func (e SearchSortOrder) IsValid() bool {
	switch e {
	case SearchSortOrderAsc, SearchSortOrderDesc:
		return true
	}
	return false
}

func (e SearchSortOrder) String() string {
	return string(e)
}

func (e *SearchSortOrder) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SearchSortOrder(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SearchSortOrder", str)
	}
	return nil
}

func (e SearchSortOrder) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SearchSortOrder) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SearchSortOrder) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SearchStationSortBy string

const (
	SearchStationSortByRelevance    SearchStationSortBy = "RELEVANCE"
	SearchStationSortByName         SearchStationSortBy = "NAME"
	SearchStationSortByRoutineCount SearchStationSortBy = "ROUTINE_COUNT"
	SearchStationSortByLastUpdate   SearchStationSortBy = "LAST_UPDATE"
	SearchStationSortByCreatedAt    SearchStationSortBy = "CREATED_AT"
)

var AllSearchStationSortBy = []SearchStationSortBy{
	SearchStationSortByRelevance,
	SearchStationSortByName,
	SearchStationSortByRoutineCount,
	SearchStationSortByLastUpdate,
	SearchStationSortByCreatedAt,
}

func (e SearchStationSortBy) IsValid() bool {
	switch e {
	case SearchStationSortByRelevance, SearchStationSortByName, SearchStationSortByRoutineCount, SearchStationSortByLastUpdate, SearchStationSortByCreatedAt:
		return true
	}
	return false
}

func (e SearchStationSortBy) String() string {
	return string(e)
}

func (e *SearchStationSortBy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SearchStationSortBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SearchStationSortBy", str)
	}
	return nil
}

func (e SearchStationSortBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SearchStationSortBy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SearchStationSortBy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SearchThemeSortBy string

const (
	SearchThemeSortByRelevance  SearchThemeSortBy = "RELEVANCE"
	SearchThemeSortByName       SearchThemeSortBy = "NAME"
	SearchThemeSortByLastUpdate SearchThemeSortBy = "LAST_UPDATE"
	SearchThemeSortByCreatedAt  SearchThemeSortBy = "CREATED_AT"
)

var AllSearchThemeSortBy = []SearchThemeSortBy{
	SearchThemeSortByRelevance,
	SearchThemeSortByName,
	SearchThemeSortByLastUpdate,
	SearchThemeSortByCreatedAt,
}

func (e SearchThemeSortBy) IsValid() bool {
	switch e {
	case SearchThemeSortByRelevance, SearchThemeSortByName, SearchThemeSortByLastUpdate, SearchThemeSortByCreatedAt:
		return true
	}
	return false
}

func (e SearchThemeSortBy) String() string {
	return string(e)
}

func (e *SearchThemeSortBy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SearchThemeSortBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SearchThemeSortBy", str)
	}
	return nil
}

func (e SearchThemeSortBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SearchThemeSortBy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SearchThemeSortBy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SearchUserSortBy string

const (
	SearchUserSortByRelevance  SearchUserSortBy = "RELEVANCE"
	SearchUserSortByName       SearchUserSortBy = "NAME"
	SearchUserSortByLastActive SearchUserSortBy = "LAST_ACTIVE"
	SearchUserSortByCreatedAt  SearchUserSortBy = "CREATED_AT"
)

var AllSearchUserSortBy = []SearchUserSortBy{
	SearchUserSortByRelevance,
	SearchUserSortByName,
	SearchUserSortByLastActive,
	SearchUserSortByCreatedAt,
}

func (e SearchUserSortBy) IsValid() bool {
	switch e {
	case SearchUserSortByRelevance, SearchUserSortByName, SearchUserSortByLastActive, SearchUserSortByCreatedAt:
		return true
	}
	return false
}

func (e SearchUserSortBy) String() string {
	return string(e)
}

func (e *SearchUserSortBy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SearchUserSortBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SearchUserSortBy", str)
	}
	return nil
}

func (e SearchUserSortBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SearchUserSortBy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SearchUserSortBy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
