package developmentroutes

import (
	"time"

	"github.com/gin-gonic/gin"

	interceptors "github.com/HiIamJeff67/notezy-backend/app/interceptors"
	middlewares "github.com/HiIamJeff67/notezy-backend/app/middlewares"
	enums "github.com/HiIamJeff67/notezy-backend/app/models/schemas/enums"
	modules "github.com/HiIamJeff67/notezy-backend/app/modules"
)

func configureDevelopmentBlockPackRoutes(router *gin.RouterGroup) {
	if router == nil {
		router = DevelopmentAPIRouterGroup
	}

	blockPackModule := modules.NewBlockPackModule()

	blockPackRoutes := router.Group("/block-packs")
	defaultMiddlewares := []gin.HandlerFunc{
		middlewares.UnauthorizedRateLimitMiddleware(),
		middlewares.TimeoutMiddleware(3 * time.Second),
		middlewares.AuthMiddleware(),
		interceptors.ShareableResponseWriterInterceptor(
			interceptors.RefreshTokenInterceptor,
			interceptors.EmbeddedInterceptor,
		),
	}
	{
		blockPackRoutes.GET(
			"/:blockPackId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("getMyBlockPackById"),
					middlewares.ApplyMeterMiddleware("server.requests.blockPack.getMyBlockPackById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				blockPackModule.Binder.BindGetMyBlockPackById(
					blockPackModule.Controller.GetMyBlockPackById,
				),
			)...,
		)
		blockPackRoutes.GET(
			"/:blockPackId/parent",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("getMyBlockPackAndItsParentById"),
					middlewares.ApplyMeterMiddleware("server.requests.blockPack.getMyBlockPackAndItsParentById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				blockPackModule.Binder.BindGetMyBlockPackAndItsParentById(
					blockPackModule.Controller.GetMyBlockPackAndItsParentById,
				),
			)...,
		)
		blockPackRoutes.GET(
			"/sub-shelf/:parentSubShelfId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("getMyBlockPacksByParentSubShelfId"),
					middlewares.ApplyMeterMiddleware("server.requests.blockPack.getMyBlockPacksByParentSubShelfId"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				blockPackModule.Binder.BindGetMyBlockPacksByParentSubShelfId(
					blockPackModule.Controller.GetMyBlockPacksByParentSubShelfId,
				),
			)...,
		)
		blockPackRoutes.GET(
			"/root-shelf/:rootShelfId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("getAllMyBlockPacksByRootShelfId"),
					middlewares.ApplyMeterMiddleware("server.requests.blockPack.getAllMyBlockPacksByRootShelfId"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				blockPackModule.Binder.BindGetAllMyBlockPacksByRootShelfId(
					blockPackModule.Controller.GetAllMyBlockPacksByRootShelfId,
				),
			)...,
		)
		blockPackRoutes.POST(
			"/sub-shelf/:parentSubShelfId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("createBlockPack"),
					middlewares.ApplyMeterMiddleware("server.requests.blockPack.createBlockPack"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				blockPackModule.Binder.BindCreateBlockPack(
					blockPackModule.Controller.CreateBlockPack,
				),
			)...,
		)
		blockPackRoutes.POST(
			"/batch",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("createBlockPacks"),
					middlewares.ApplyMeterMiddleware("server.requests.blockPack.CreateBlockPacks"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				blockPackModule.Binder.BindCreateBlockPacks(
					blockPackModule.Controller.CreateBlockPacks,
				),
			)...,
		)
		blockPackRoutes.PUT(
			"/:blockPackId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("updateMyBlockPackById"),
					middlewares.ApplyMeterMiddleware("server.requests.blockPack.updateMyBlockPackById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				blockPackModule.Binder.BindUpdateMyBlockPackById(
					blockPackModule.Controller.UpdateMyBlockPackById,
				),
			)...,
		)
		blockPackRoutes.PUT(
			"/batch",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("updateMyBlockPacksByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.blockPack.UpdateMyBlockPacksByIds"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				blockPackModule.Binder.BindUpdateMyBlockPacksByIds(
					blockPackModule.Controller.UpdateMyBlockPacksByIds,
				),
			)...,
		)
		blockPackRoutes.PUT(
			"/:blockPackId/position",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("moveMyBlockPackById"),
					middlewares.ApplyMeterMiddleware("server.requests.blockPack.moveMyBlockPackById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				blockPackModule.Binder.BindMoveMyBlockPackByParentSubShelfId(
					blockPackModule.Controller.MoveMyBlockPackByParentSubShelfId,
				),
			)...,
		)
		blockPackRoutes.PUT(
			"/position",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("moveMyBlockPacksByParentSubShelfId"),
					middlewares.ApplyMeterMiddleware("server.requests.blockPack.moveMyBlockPacksByParentSubShelfId"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				blockPackModule.Binder.BindMoveMyBlockPacksByParentSubShelfId(
					blockPackModule.Controller.MoveMyBlockPacksByParentSubShelfId,
				),
			)...,
		)
		blockPackRoutes.PUT(
			"/batch/position",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("moveMyBlockPacksByParentSubShelfIds"),
					middlewares.ApplyMeterMiddleware("server.requests.blockPack.moveMyBlockPacksByParentSubShelfIds"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				blockPackModule.Binder.BindMoveMyBlockPacksByParentSubShelfIds(
					blockPackModule.Controller.MoveMyBlockPacksByParentSubShelfIds,
				),
			)...,
		)
		blockPackRoutes.PATCH(
			"/:blockPackId/restore",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("restoreMyBlockPackById"),
					middlewares.ApplyMeterMiddleware("server.requests.blockPack.restoreMyBlockPackById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				blockPackModule.Binder.BindRestoreMyBlockPackById(
					blockPackModule.Controller.RestoreMyBlockPackById,
				),
			)...,
		)
		blockPackRoutes.PATCH(
			"/batch/restore",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("restoreMyBlockPacksByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.blockPack.restoreMyBlockPacksByIds"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				blockPackModule.Binder.BindRestoreMyBlockPacksByIds(
					blockPackModule.Controller.RestoreMyBlockPacksByIds,
				),
			)...,
		)
		blockPackRoutes.DELETE(
			"/:blockPackId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("deleteMyBlockPackById"),
					middlewares.ApplyMeterMiddleware("server.requests.blockPack.deleteMyBlockPackById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				blockPackModule.Binder.BindDeleteMyBlockPackById(
					blockPackModule.Controller.DeleteMyBlockPackById,
				),
			)...,
		)
		blockPackRoutes.DELETE(
			"/batch",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("deleteMyBlockPacksByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.blockPack.deleteMyBlockPacksByIds"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				blockPackModule.Binder.BindDeleteMyBlockPacksByIds(
					blockPackModule.Controller.DeleteMyBlockPacksByIds,
				),
			)...,
		)
	}
}
