package developmentroutes

import (
	"time"

	"github.com/gin-gonic/gin"

	adapters "github.com/HiIamJeff67/notezy-backend/app/adapters"
	interceptors "github.com/HiIamJeff67/notezy-backend/app/interceptors"
	middlewares "github.com/HiIamJeff67/notezy-backend/app/middlewares"
	enums "github.com/HiIamJeff67/notezy-backend/app/models/schemas/enums"
	modules "github.com/HiIamJeff67/notezy-backend/app/modules"
)

func configureDevelopmentMaterialRoutes(router *gin.RouterGroup) {
	if router == nil {
		router = DevelopmentAPIRouterGroup
	}

	materialModule := modules.NewMaterialModule()

	materialRoutes := router.Group("/material")
	defaultMiddlewares := []gin.HandlerFunc{
		middlewares.UnauthorizedRateLimitMiddleware(),
		middlewares.TimeoutMiddleware(3 * time.Second),
		middlewares.AuthMiddleware(),
		interceptors.ShareableResponseWriterInterceptor(
			interceptors.RefreshTokenInterceptor,
			interceptors.EmbeddedInterceptor,
		),
	}
	{
		materialRoutes.GET(
			"/getMyMaterialById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("getMyMaterialById"),
					middlewares.ApplyMeterMiddleware("server.requests.material.getMyMaterialById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				materialModule.Binder.BindGetMyMaterialById(
					materialModule.Controller.GetMyMaterialById,
				),
			)...,
		)
		materialRoutes.GET(
			"/getMyMaterialAndItsParentById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("getMyMaterialAndItsParentById"),
					middlewares.ApplyMeterMiddleware("server.requests.material.getMyMaterialAndItsParentById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				materialModule.Binder.BindGetMyMaterialAndItsParentById(
					materialModule.Controller.GetMyMaterialAndItsParentById,
				),
			)...,
		)
		materialRoutes.GET(
			"/getMyMaterialsByParentSubShelfId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("getMyMaterialsByParentSubShelfId"),
					middlewares.ApplyMeterMiddleware("server.requests.material.getMyMaterialsByParentSubShelfId"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				materialModule.Binder.BindGetMyMaterialsByParentSubShelfId(
					materialModule.Controller.GetMyMaterialsByParentSubShelfId,
				),
			)...,
		)
		materialRoutes.GET(
			"/getAllMyMaterialsByRootShelfId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("getAllMyMaterialsByRootShelfId"),
					middlewares.ApplyMeterMiddleware("server.requests.material.getAllMyMaterialsByRootShelfId"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				materialModule.Binder.BindGetAllMyMaterialsByRootShelfId(
					materialModule.Controller.GetAllMyMaterialsByRootShelfId,
				),
			)...,
		)
		materialRoutes.POST(
			"/createMyMaterial",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("createMyMaterial"),
					middlewares.ApplyMeterMiddleware("server.requests.material.createMyMaterial"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				materialModule.Binder.BindCreateMyMaterial(
					materialModule.Controller.CreateMyMaterial,
				),
			)...,
		)
		materialRoutes.PUT(
			"/updateMyMaterialById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("updateMyMaterialById"),
					middlewares.ApplyMeterMiddleware("server.requests.material.updateMyMaterialById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				materialModule.Binder.BindUpdateMyMaterialById(
					materialModule.Controller.UpdateMyMaterialById,
				),
			)...,
		)
		materialRoutes.PUT(
			"/saveMyMaterialById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("saveMyMaterialById"),
					middlewares.ApplyMeterMiddleware("server.requests.material.saveMyMaterialById"),
					adapters.MultipartAdapter(),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				materialModule.Binder.BindSaveMyMaterialById(
					materialModule.Controller.SaveMyMaterialById,
				),
			)...,
		)
		materialRoutes.PUT(
			"/moveMyMaterialById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("moveMyMaterialById"),
					middlewares.ApplyMeterMiddleware("server.requests.material.moveMyMaterialById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				materialModule.Binder.BindMoveMyMaterialById(
					materialModule.Controller.MoveMyMaterialById,
				),
			)...,
		)
		materialRoutes.PUT(
			"/moveMyMaterialsByIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("moveMyMaterialsByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.material.moveMyMaterialsByIds"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				materialModule.Binder.BindMoveMyMaterialsByIds(
					materialModule.Controller.MoveMyMaterialsByIds,
				),
			)...,
		)
		materialRoutes.PATCH(
			"/restoreMyMaterialById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("restoreMyMaterialById"),
					middlewares.ApplyMeterMiddleware("server.requests.material.restoreMyMaterialById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				materialModule.Binder.BindRestoreMyMaterialById(
					materialModule.Controller.RestoreMyMaterialById,
				),
			)...,
		)
		materialRoutes.PATCH(
			"/restoreMyMaterialsByIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("restoreMyMaterialsByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.material.restoreMyMaterialsByIds"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				materialModule.Binder.BindRestoreMyMaterialsByIds(
					materialModule.Controller.RestoreMyMaterialsByIds,
				),
			)...,
		)
		materialRoutes.DELETE(
			"/deleteMyMaterialById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("deleteMyMaterialById"),
					middlewares.ApplyMeterMiddleware("server.requests.material.deleteMyMaterialById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				materialModule.Binder.BindDeleteMyMaterialById(
					materialModule.Controller.DeleteMyMaterialById,
				),
			)...,
		)
		materialRoutes.DELETE(
			"/deleteMyMaterialsByIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("deleteMyMaterialsByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.material.deleteMyMaterialsByIds"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				materialModule.Binder.BindDeleteMyMaterialsByIds(
					materialModule.Controller.DeleteMyMaterialsByIds,
				),
			)...,
		)
	}
}
