package developmentroutes

import (
	"time"

	"github.com/gin-gonic/gin"

	interceptors "github.com/HiIamJeff67/notezy-backend/app/interceptors"
	middlewares "github.com/HiIamJeff67/notezy-backend/app/middlewares"
	enums "github.com/HiIamJeff67/notezy-backend/app/models/schemas/enums"
	modules "github.com/HiIamJeff67/notezy-backend/app/modules"
)

func configureDevelopmentRootShelfRoutes(router *gin.RouterGroup) {
	if router == nil {
		router = DevelopmentAPIRouterGroup
	}

	rootShelfModule := modules.NewRootShelfModule()

	rootShelfRoutes := router.Group("/rootShelf")
	defaultMiddlewares := []gin.HandlerFunc{
		middlewares.UnauthorizedRateLimitMiddleware(),
		middlewares.TimeoutMiddleware(1 * time.Second),
		middlewares.AuthMiddleware(),
		interceptors.ShareableResponseWriterInterceptor(
			interceptors.RefreshTokenInterceptor,
			interceptors.EmbeddedInterceptor,
		),
	}
	{
		rootShelfRoutes.GET(
			"/getMyRootShelfById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("getMyRootShelfById"),
					middlewares.ApplyMeterMiddleware("server.requests.rootShelf.getMyRootShelfById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				rootShelfModule.Binder.BindGetMyRootShelfById(
					rootShelfModule.Controller.GetMyRootShelfById,
				),
			)...,
		)
		rootShelfRoutes.GET(
			"/searchRecentRootShelves",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("searchRecentRootShelves"),
					middlewares.ApplyMeterMiddleware("server.requests.rootShelf.searchRecentRootShelves"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				rootShelfModule.Binder.BindSearchRecentRootShelves(
					rootShelfModule.Controller.SearchRecentRootShelves,
				),
			)...,
		)
		rootShelfRoutes.POST(
			"/createRootShelf",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("createRootShelf"),
					middlewares.ApplyMeterMiddleware("server.requests.rootShelf.createRootShelf"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				rootShelfModule.Binder.BindCreateRootShelf(
					rootShelfModule.Controller.CreateRootShelf,
				),
			)...,
		)
		rootShelfRoutes.POST(
			"/createRootShelves",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("createRootShelves"),
					middlewares.ApplyMeterMiddleware("server.requests.rootShelf.createRootShelves"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				rootShelfModule.Binder.BindCreateRootShelves(
					rootShelfModule.Controller.CreateRootShelves,
				),
			)...,
		)
		rootShelfRoutes.PUT(
			"/updateMyRootShelfById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("updateMyRootShelfById"),
					middlewares.ApplyMeterMiddleware("server.requests.rootShelf.updateMyRootShelfById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Admin),
				),
				rootShelfModule.Binder.BindUpdateMyRootShelfById(
					rootShelfModule.Controller.UpdateMyRootShelfById,
				),
			)...,
		)
		rootShelfRoutes.PUT(
			"/updateMyRootShelvesByIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("updateMyRootShelvesByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.rootShelf.updateMyRootShelvesByIds"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Admin),
				),
				rootShelfModule.Binder.BindUpdateMyRootShelvesByIds(
					rootShelfModule.Controller.UpdateMyRootShelvesByIds,
				),
			)...,
		)
		rootShelfRoutes.PATCH(
			"/restoreMyRootShelfById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("restoreMyRootShelfById"),
					middlewares.ApplyMeterMiddleware("server.requests.rootShelf.restoreMyRootShelfById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Owner),
				),
				rootShelfModule.Binder.BindRestoreMyRootShelfById(
					rootShelfModule.Controller.RestoreMyRootShelfById,
				),
			)...,
		)
		rootShelfRoutes.PATCH(
			"/restoreMyRootShelvesByIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("restoreMyRootShelvesByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.rootShelf.restoreMyRootShelvesByIds"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Owner),
				),
				rootShelfModule.Binder.BindRestoreMyRootShelvesByIds(
					rootShelfModule.Controller.RestoreMyRootShelvesByIds,
				),
			)...,
		)
		rootShelfRoutes.DELETE(
			"/deleteMyRootShelfById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("deleteMyRootShelfById"),
					middlewares.ApplyMeterMiddleware("server.requests.rootShelf.deleteMyRootShelfById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				rootShelfModule.Binder.BindDeleteMyRootShelfById(
					rootShelfModule.Controller.DeleteMyRootShelfById,
				),
			)...,
		)
		rootShelfRoutes.DELETE(
			"/deleteMyRootShelvesByIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("deleteMyRootShelvesByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.rootShelf.deleteMyRootShelvesByIds"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Owner),
				),
				rootShelfModule.Binder.BindDeleteMyRootShelvesByIds(
					rootShelfModule.Controller.DeleteMyRootShelvesByIds,
				),
			)...,
		)
		rootShelfRoutes.GET(
			"/:rootShelfId/permissions/:userPublicId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("getMyRootShelfPermission"),
					middlewares.ApplyMeterMiddleware("server.requests.rootShelf.getMyRootShelfPermission"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				rootShelfModule.Binder.BindGetMyRootShelfPermission(
					rootShelfModule.Controller.GetMyRootShelfPermission,
				),
			)...,
		)
		rootShelfRoutes.POST(
			"/:rootShelfId/permissions/:userPublicId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("createMyRootShelfPermission"),
					middlewares.ApplyMeterMiddleware("server.requests.rootShelf.createMyRootShelfPermission"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Admin),
				),
				rootShelfModule.Binder.BindCreateMyRootShelfPermission(
					rootShelfModule.Controller.CreateMyRootShelfPermission,
				),
			)...,
		)
		rootShelfRoutes.PUT(
			"/:rootShelfId/permissions/:userPublicId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("upsertMyRootShelfPermission"),
					middlewares.ApplyMeterMiddleware("server.requests.rootShelf.upsertMyRootShelfPermission"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Admin),
				),
				rootShelfModule.Binder.BindUpsertMyRootShelfPermission(
					rootShelfModule.Controller.UpsertMyRootShelfPermission,
				),
			)...,
		)
		rootShelfRoutes.PUT(
			"/:rootShelfId/permissions",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("upsertMyRootShelfPermissions"),
					middlewares.ApplyMeterMiddleware("server.requests.rootShelf.upsertMyRootShelfPermissions"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Admin),
				),
				rootShelfModule.Binder.BindUpsertMyRootShelfPermissions(
					rootShelfModule.Controller.UpsertMyRootShelfPermissions,
				),
			)...,
		)
		rootShelfRoutes.PATCH(
			"/:rootShelfId/permissions/:userPublicId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("updateMyRootShelfPermission"),
					middlewares.ApplyMeterMiddleware("server.requests.rootShelf.updateMyRootShelfPermission"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Admin),
				),
				rootShelfModule.Binder.BindUpdateMyRootShelfPermission(
					rootShelfModule.Controller.UpdateMyRootShelfPermission,
				),
			)...,
		)
		rootShelfRoutes.POST(
			"/:rootShelfId/ownership-transfer",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("transferMyRootShelfOwnership"),
					middlewares.ApplyMeterMiddleware("server.requests.rootShelf.transferMyRootShelfOwnership"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Owner),
				),
				rootShelfModule.Binder.BindTransferMyRootShelfOwnership(
					rootShelfModule.Controller.TransferMyRootShelfOwnership,
				),
			)...,
		)
		rootShelfRoutes.DELETE(
			"/:rootShelfId/permissions/:userPublicId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("deleteMyRootShelfPermission"),
					middlewares.ApplyMeterMiddleware("server.requests.rootShelf.deleteMyRootShelfPermission"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Admin),
				),
				rootShelfModule.Binder.BindDeleteMyRootShelfPermission(
					rootShelfModule.Controller.DeleteMyRootShelfPermission,
				),
			)...,
		)
		rootShelfRoutes.DELETE(
			"/:rootShelfId/permissions",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("deleteMyRootShelfPermissions"),
					middlewares.ApplyMeterMiddleware("server.requests.rootShelf.deleteMyRootShelfPermissions"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Admin),
				),
				rootShelfModule.Binder.BindDeleteMyRootShelfPermissions(
					rootShelfModule.Controller.DeleteMyRootShelfPermissions,
				),
			)...,
		)
		rootShelfRoutes.DELETE(
			"/:rootShelfId/leave",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("leaveMyRootShelf"),
					middlewares.ApplyMeterMiddleware("server.requests.rootShelf.leaveMyRootShelf"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				rootShelfModule.Binder.BindLeaveMyRootShelf(
					rootShelfModule.Controller.LeaveMyRootShelf,
				),
			)...,
		)
		rootShelfRoutes.DELETE(
			"/leave",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("leaveMyRootShelves"),
					middlewares.ApplyMeterMiddleware("server.requests.rootShelf.leaveMyRootShelves"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				rootShelfModule.Binder.BindLeaveMyRootShelves(
					rootShelfModule.Controller.LeaveMyRootShelves,
				),
			)...,
		)
	}
}
