package developmentroutes

import (
	"time"

	"github.com/gin-gonic/gin"

	interceptors "github.com/HiIamJeff67/notezy-backend/app/interceptors"
	middlewares "github.com/HiIamJeff67/notezy-backend/app/middlewares"
	enums "github.com/HiIamJeff67/notezy-backend/app/models/schemas/enums"
	modules "github.com/HiIamJeff67/notezy-backend/app/modules"
)

func configureDevelopmentRoutineRoutes(router *gin.RouterGroup) {
	if router == nil {
		router = DevelopmentAPIRouterGroup
	}

	routineModule := modules.NewRoutineModule()

	routineRoutes := router.Group("/routine")
	defaultMiddlewares := []gin.HandlerFunc{
		middlewares.UnauthorizedRateLimitMiddleware(),
		middlewares.TimeoutMiddleware(3 * time.Second),
		middlewares.AuthMiddleware(),
		interceptors.ShareableResponseWriterInterceptor(
			interceptors.RefreshTokenInterceptor,
			interceptors.EmbeddedInterceptor,
		),
	}
	{
		routineRoutes.GET(
			"/getMyRoutineById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("getMyRoutineById"),
					middlewares.ApplyMeterMiddleware("server.requests.routine.getMyRoutineById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				routineModule.Binder.BindGetMyRoutineById(
					routineModule.Controller.GetMyRoutineById,
				),
			)...,
		)
		routineRoutes.GET(
			"getMyRoutinesByStationId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("getMyRoutinesByStationId"),
					middlewares.ApplyMeterMiddleware("server.requests.routine.getMyRoutinesByStationId"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				routineModule.Binder.BindGetMyRoutinesByStationId(
					routineModule.Controller.GetMyRoutinesByStationId,
				),
			)...,
		)
		routineRoutes.GET(
			"/getAllMyRoutinesByTimeRange",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("getAllMyRoutinesByTimeRange"),
					middlewares.ApplyMeterMiddleware("server.requests.routine.getAllMyRoutinesByTimeRange"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				routineModule.Binder.BindGetAllMyRoutinesByTimeRange(
					routineModule.Controller.GetAllMyRoutinesByTimeRange,
				),
			)...,
		)
		routineRoutes.GET(
			"/visualizeMyRoutineStatusCount",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("visualizeMyRoutineStatusCount"),
					middlewares.ApplyMeterMiddleware("server.requests.routine.visualizeMyRoutineStatusCount"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				routineModule.Binder.BindVisualizeMyRoutineStatusCount(
					routineModule.Controller.VisualizeMyRoutineStatusCount,
				),
			)...,
		)
		routineRoutes.GET(
			"/visualizeMyRoutinePeriodCount",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("visualizeMyRoutinePeriodCount"),
					middlewares.ApplyMeterMiddleware("server.requests.routine.visualizeMyRoutinePeriodCount"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				routineModule.Binder.BindVisualizeMyRoutinePeriodCount(
					routineModule.Controller.VisualizeMyRoutinePeriodCount,
				),
			)...,
		)
		routineRoutes.GET(
			"/visualizeMyRoutineScheduledStartAtCount",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("visualizeMyRoutineScheduledStartAtCount"),
					middlewares.ApplyMeterMiddleware("server.requests.routine.visualizeMyRoutineScheduledStartAtCount"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				routineModule.Binder.BindVisualizeMyRoutineScheduledStartAtCount(
					routineModule.Controller.VisualizeMyRoutineScheduledStartAtCount,
				),
			)...,
		)
		routineRoutes.GET(
			"/visualizeMyRoutineScheduledEndAtCount",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("visualizeMyRoutineScheduledEndAtCount"),
					middlewares.ApplyMeterMiddleware("server.requests.routine.visualizeMyRoutineScheduledEndAtCount"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				routineModule.Binder.BindVisualizeMyRoutineScheduledEndAtCount(
					routineModule.Controller.VisualizeMyRoutineScheduledEndAtCount,
				),
			)...,
		)
		routineRoutes.POST(
			"/createRoutineByStationId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("createRoutineByStationId"),
					middlewares.ApplyMeterMiddleware("server.requests.routine.createRoutineByStationId"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				routineModule.Binder.BindCreateRoutineByStationId(
					routineModule.Controller.CreateRoutineByStationId,
				),
			)...,
		)
		routineRoutes.POST(
			"/createRoutinesByStationIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("createRoutinesByStationIds"),
					middlewares.ApplyMeterMiddleware("server.requests.routine.createRoutinesByStationIds"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				routineModule.Binder.BindCreateRoutinesByStationIds(
					routineModule.Controller.CreateRoutinesByStationIds,
				),
			)...,
		)
		routineRoutes.PUT(
			"/updateMyRoutineById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("updateMyRoutineById"),
					middlewares.ApplyMeterMiddleware("server.requests.routine.updateMyRoutineById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				routineModule.Binder.BindUpdateMyRoutineById(
					routineModule.Controller.UpdateMyRoutineById,
				),
			)...,
		)
		routineRoutes.PUT(
			"/updateMyRoutinesByIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("updateMyRoutinesByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.routine.updateMyRoutinesByIds"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				routineModule.Binder.BindUpdateMyRoutinesByIds(
					routineModule.Controller.UpdateMyRoutinesByIds,
				),
			)...,
		)
		routineRoutes.POST(
			"/linkRoutineTagById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("linkRoutineTagById"),
					middlewares.ApplyMeterMiddleware("server.requests.routine.linkRoutineTagById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				routineModule.Binder.BindLinkRoutineTagById(
					routineModule.Controller.LinkRoutineTagById,
				),
			)...,
		)
		routineRoutes.POST(
			"/linkRoutineTagsByIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("linkRoutineTagsByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.routine.linkRoutineTagsByIds"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				routineModule.Binder.BindLinkRoutineTagsByIds(
					routineModule.Controller.LinkRoutineTagsByIds,
				),
			)...,
		)
		routineRoutes.POST(
			"/linkRoutineItemById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("linkRoutineItemById"),
					middlewares.ApplyMeterMiddleware("server.requests.routine.linkRoutineItemById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				routineModule.Binder.BindLinkRoutineItemById(
					routineModule.Controller.LinkRoutineItemById,
				),
			)...,
		)
		routineRoutes.POST(
			"/linkRoutineItemsByIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("linkRoutineItemsByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.routine.linkRoutineItemsByIds"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				routineModule.Binder.BindLinkRoutineItemsByIds(
					routineModule.Controller.LinkRoutineItemsByIds,
				),
			)...,
		)
		routineRoutes.PATCH(
			"/restoreMyRoutineById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("restoreMyRoutineById"),
					middlewares.ApplyMeterMiddleware("server.requests.routine.restoreMyRoutineById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				routineModule.Binder.BindRestoreMyRoutineById(
					routineModule.Controller.RestoreMyRoutineById,
				),
			)...,
		)
		routineRoutes.PATCH(
			"/restoreMyRoutinesByIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("restoreMyRoutinesByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.routine.restoreMyRoutinesByIds"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				routineModule.Binder.BindRestoreMyRoutinesByIds(
					routineModule.Controller.RestoreMyRoutinesByIds,
				),
			)...,
		)
		routineRoutes.DELETE(
			"/deleteMyRoutineById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("deleteMyRoutineById"),
					middlewares.ApplyMeterMiddleware("server.requests.routine.deleteMyRoutineById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				routineModule.Binder.BindDeleteMyRoutineById(
					routineModule.Controller.DeleteMyRoutineById,
				),
			)...,
		)
		routineRoutes.DELETE(
			"/deleteMyRoutinesByIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("deleteMyRoutinesByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.routine.deleteMyRoutinesByIds"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				routineModule.Binder.BindDeleteMyRoutinesByIds(
					routineModule.Controller.DeleteMyRoutinesByIds,
				),
			)...,
		)
		routineRoutes.DELETE(
			"/hardDeleteMyRoutineById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("hardDeleteMyRoutineById"),
					middlewares.ApplyMeterMiddleware("server.requests.routine.hardDeleteMyRoutineById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				routineModule.Binder.BindHardDeleteMyRoutineById(
					routineModule.Controller.HardDeleteMyRoutineById,
				),
			)...,
		)
		routineRoutes.DELETE(
			"/hardDeleteMyRoutinesByIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("hardDeleteMyRoutinesByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.routine.hardDeleteMyRoutinesByIds"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				routineModule.Binder.BindHardDeleteMyRoutinesByIds(
					routineModule.Controller.HardDeleteMyRoutinesByIds,
				),
			)...,
		)
	}
}
