package developmentroutes

import (
	"time"

	"github.com/gin-gonic/gin"

	interceptors "github.com/HiIamJeff67/notezy-backend/app/interceptors"
	middlewares "github.com/HiIamJeff67/notezy-backend/app/middlewares"
	enums "github.com/HiIamJeff67/notezy-backend/app/models/schemas/enums"
	modules "github.com/HiIamJeff67/notezy-backend/app/modules"
)

func configureDevelopmentRoutineTaskRoutes(router *gin.RouterGroup) {
	if router == nil {
		router = DevelopmentAPIRouterGroup
	}

	routineTaskModule := modules.NewRoutineTaskModule()

	routineTaskRoutes := router.Group("/routine-tasks")
	defaultMiddlewares := []gin.HandlerFunc{
		middlewares.UnauthorizedRateLimitMiddleware(),
		middlewares.TimeoutMiddleware(3 * time.Second),
		middlewares.AuthMiddleware(),
		interceptors.ShareableResponseWriterInterceptor(
			interceptors.RefreshTokenInterceptor,
			interceptors.EmbeddedInterceptor,
		),
	}
	{
		routineTaskRoutes.GET(
			"/:routineTaskId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("getMyRoutineTaskById"),
					middlewares.ApplyMeterMiddleware("server.requests.routineTask.getMyRoutineTaskById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				routineTaskModule.Binder.BindGetMyRoutineTaskById(
					routineTaskModule.Controller.GetMyRoutineTaskById,
				),
			)...,
		)
		routineTaskRoutes.GET(
			"/routines",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("getAllMyRoutineTasksByRoutineIds"),
					middlewares.ApplyMeterMiddleware("server.requests.routineTask.getAllMyRoutineTasksByRoutineIds"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				routineTaskModule.Binder.BindGetAllMyRoutineTasksByRoutineIds(
					routineTaskModule.Controller.GetAllMyRoutineTasksByRoutineIds,
				),
			)...,
		)
		routineTaskRoutes.GET(
			"/",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("getAllMyRoutineTasks"),
					middlewares.ApplyMeterMiddleware("server.requests.routineTask.getAllMyRoutineTasks"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				routineTaskModule.Binder.BindGetAllMyRoutineTasks(
					routineTaskModule.Controller.GetAllMyRoutineTasks,
				),
			)...,
		)
		routineTaskRoutes.POST(
			"/routine/:routineId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("createRoutineTaskByRoutineId"),
					middlewares.ApplyMeterMiddleware("server.requests.routineTask.createRoutineTaskByRoutineId"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				routineTaskModule.Binder.BindCreateRoutineTaskByRoutineId(
					routineTaskModule.Controller.CreateRoutineTaskByRoutineId,
				),
			)...,
		)
		routineTaskRoutes.PUT(
			"/:routineTaskId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("updateMyRoutineTaskById"),
					middlewares.ApplyMeterMiddleware("server.requests.routineTask.updateMyRoutineTaskById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				routineTaskModule.Binder.BindUpdateMyRoutineTaskById(
					routineTaskModule.Controller.UpdateMyRoutineTaskById,
				),
			)...,
		)
		routineTaskRoutes.PUT(
			"/:routineTaskId/suspension",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("pauseMyRoutineTaskById"),
					middlewares.ApplyMeterMiddleware("server.requests.routineTask.pauseMyRoutineTaskById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				routineTaskModule.Binder.BindPauseMyRoutineTaskById(
					routineTaskModule.Controller.PauseMyRoutineTaskById,
				),
			)...,
		)
		routineTaskRoutes.DELETE(
			"/:routineTaskId/suspension",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("resumeMyRoutineTaskById"),
					middlewares.ApplyMeterMiddleware("server.requests.routineTask.resumeMyRoutineTaskById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				routineTaskModule.Binder.BindResumeMyRoutineTaskById(
					routineTaskModule.Controller.ResumeMyRoutineTaskById,
				),
			)...,
		)
		routineTaskRoutes.DELETE(
			"/:routineTaskId/permanently",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("hardDeleteMyRoutineTaskById"),
					middlewares.ApplyMeterMiddleware("server.requests.routineTask.hardDeleteMyRoutineTaskById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				routineTaskModule.Binder.BindHardDeleteMyRoutineTaskById(
					routineTaskModule.Controller.HardDeleteMyRoutineTaskById,
				),
			)...,
		)
		routineTaskRoutes.DELETE(
			"/batch/permanently",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("hardDeleteMyRoutineTasksByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.routineTask.hardDeleteMyRoutineTasksByIds"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Write),
				),
				routineTaskModule.Binder.BindHardDeleteMyRoutineTasksByIds(
					routineTaskModule.Controller.HardDeleteMyRoutineTasksByIds,
				),
			)...,
		)
	}

	/* ============================== Routes for Visualization ============================== */

	visualizationRoutes := router.Group("/routine-tasks/visualizations")
	visualizationMiddlewares := []gin.HandlerFunc{
		middlewares.UnauthorizedRateLimitMiddleware(),
		middlewares.TimeoutMiddleware(3 * time.Second),
		middlewares.AuthMiddleware(),
		interceptors.ShareableResponseWriterInterceptor(
			interceptors.RefreshTokenInterceptor,
			interceptors.EmbeddedInterceptor,
		),
	}
	{
		visualizationRoutes.GET(
			"/status-count",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("visualizeMyRoutineTaskStatusCount"),
					middlewares.ApplyMeterMiddleware("server.requests.routineTask.visualizeMyRoutineTaskStatusCount"),
				},
				append(
					visualizationMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				routineTaskModule.Binder.BindVisualizeMyRoutineTaskStatusCount(
					routineTaskModule.Controller.VisualizeMyRoutineTaskStatusCount,
				),
			)...,
		)
		visualizationRoutes.GET(
			"/purpose-count",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("visualizeMyRoutineTaskPurposeCount"),
					middlewares.ApplyMeterMiddleware("server.requests.routineTask.visualizeMyRoutineTaskPurposeCount"),
				},
				append(
					visualizationMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				routineTaskModule.Binder.BindVisualizeMyRoutineTaskPurposeCount(
					routineTaskModule.Controller.VisualizeMyRoutineTaskPurposeCount,
				),
			)...,
		)
		visualizationRoutes.GET(
			"/scheduled-at-count",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("visualizeMyRoutineTaskScheduledAtCount"),
					middlewares.ApplyMeterMiddleware("server.requests.routineTask.visualizeMyRoutineTaskScheduledAtCount"),
				},
				append(
					visualizationMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				routineTaskModule.Binder.BindVisualizeMyRoutineTaskScheduledAtCount(
					routineTaskModule.Controller.VisualizeMyRoutineTaskScheduledAtCount,
				),
			)...,
		)
		visualizationRoutes.GET(
			"/actual-started-at-count",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("visualizeMyRoutineTaskActualStartedAtCount"),
					middlewares.ApplyMeterMiddleware("server.requests.routineTask.visualizeMyRoutineTaskActualStartedAtCount"),
				},
				append(
					visualizationMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				routineTaskModule.Binder.BindVisualizeMyRoutineTaskActualStartedAtCount(
					routineTaskModule.Controller.VisualizeMyRoutineTaskActualStartedAtCount,
				),
			)...,
		)
		visualizationRoutes.GET(
			"/actual-ended-at-count",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("visualizeMyRoutineTaskActualEndedAtCount"),
					middlewares.ApplyMeterMiddleware("server.requests.routineTask.visualizeMyRoutineTaskActualEndedAtCount"),
				},
				append(
					visualizationMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				routineTaskModule.Binder.BindVisualizeMyRoutineTaskActualEndedAtCount(
					routineTaskModule.Controller.VisualizeMyRoutineTaskActualEndedAtCount,
				),
			)...,
		)
	}
}
