package developmentroutes

import (
	"time"

	"github.com/gin-gonic/gin"

	interceptors "github.com/HiIamJeff67/notezy-backend/app/interceptors"
	middlewares "github.com/HiIamJeff67/notezy-backend/app/middlewares"
	modules "github.com/HiIamJeff67/notezy-backend/app/modules"
)

func configureDevelopmentStationRoutes(router *gin.RouterGroup) {
	if router == nil {
		router = DevelopmentAPIRouterGroup
	}

	stationModule := modules.NewStationModule()

	stationRoutes := router.Group("/station")
	defaultMiddlewares := []gin.HandlerFunc{
		middlewares.UnauthorizedRateLimitMiddleware(),
		middlewares.TimeoutMiddleware(3 * time.Second),
		middlewares.AuthMiddleware(),
		interceptors.ShareableResponseWriterInterceptor(
			interceptors.RefreshTokenInterceptor,
			interceptors.EmbeddedInterceptor,
		),
	}
	{
		stationRoutes.GET(
			"/getMyStationById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("getMyStationById"),
					middlewares.ApplyMeterMiddleware("server.requests.station.getMyStationById"),
				},
				defaultMiddlewares,
				stationModule.Binder.BindGetMyStationById(
					stationModule.Controller.GetMyStationById,
				),
			)...,
		)
		stationRoutes.GET(
			"/getAllMyStations",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("getAllMyStations"),
					middlewares.ApplyMeterMiddleware("server.requests.station.getAllMyStations"),
				},
				defaultMiddlewares,
				stationModule.Binder.BindGetAllMyStations(
					stationModule.Controller.GetAllMyStations,
				),
			)...,
		)
		stationRoutes.GET(
			"/visualizeMyTotalCount",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("visualizeMyTotalCount"),
					middlewares.ApplyMeterMiddleware("server.requests.station.visualizeMyTotalCount"),
				},
				defaultMiddlewares,
				stationModule.Binder.BindVisualizeMyTotalCount(
					stationModule.Controller.VisualizeMyTotalCount,
				),
			)...,
		)
		stationRoutes.POST(
			"/createStation",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("createStation"),
					middlewares.ApplyMeterMiddleware("server.requests.station.createStation"),
				},
				defaultMiddlewares,
				stationModule.Binder.BindCreateStation(
					stationModule.Controller.CreateStation,
				),
			)...,
		)
		stationRoutes.POST(
			"/createStations",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("createStations"),
					middlewares.ApplyMeterMiddleware("server.requests.station.createStations"),
				},
				defaultMiddlewares,
				stationModule.Binder.BindCreateStations(
					stationModule.Controller.CreateStations,
				),
			)...,
		)
		stationRoutes.PUT(
			"/updateMyStationById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("updateMyStationById"),
					middlewares.ApplyMeterMiddleware("server.requests.station.updateMyStationById"),
				},
				defaultMiddlewares,
				stationModule.Binder.BindUpdateMyStationById(
					stationModule.Controller.UpdateMyStationById,
				),
			)...,
		)
		stationRoutes.PUT(
			"/updateMyStationsByIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("updateMyStationsByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.station.updateMyStationsByIds"),
				},
				defaultMiddlewares,
				stationModule.Binder.BindUpdateMyStationsByIds(
					stationModule.Controller.UpdateMyStationsByIds,
				),
			)...,
		)
		stationRoutes.PATCH(
			"/restoreMyStationById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("restoreMyStationById"),
					middlewares.ApplyMeterMiddleware("server.requests.station.restoreMyStationById"),
				},
				defaultMiddlewares,
				stationModule.Binder.BindRestoreMyStationById(
					stationModule.Controller.RestoreMyStationById,
				),
			)...,
		)
		stationRoutes.PATCH(
			"/restoreMyStationsByIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("restoreMyStationsByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.station.restoreMyStationsByIds"),
				},
				defaultMiddlewares,
				stationModule.Binder.BindRestoreMyStationsByIds(
					stationModule.Controller.RestoreMyStationsByIds,
				),
			)...,
		)
		stationRoutes.DELETE(
			"/deleteMyStationById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("deleteMyStationById"),
					middlewares.ApplyMeterMiddleware("server.requests.station.deleteMyStationById"),
				},
				defaultMiddlewares,
				stationModule.Binder.BindDeleteMyStationById(
					stationModule.Controller.DeleteMyStationById,
				),
			)...,
		)
		stationRoutes.DELETE(
			"/deleteMyStationsByIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("deleteMyStationsByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.station.deleteMyStationsByIds"),
				},
				defaultMiddlewares,
				stationModule.Binder.BindDeleteMyStationsByIds(
					stationModule.Controller.DeleteMyStationsByIds,
				),
			)...,
		)
		stationRoutes.DELETE(
			"/hardDeleteMyStationById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("hardDeleteMyStationById"),
					middlewares.ApplyMeterMiddleware("server.requests.station.hardDeleteMyStationById"),
				},
				defaultMiddlewares,
				stationModule.Binder.BindHardDeleteMyStationById(
					stationModule.Controller.HardDeleteMyStationById,
				),
			)...,
		)
		stationRoutes.DELETE(
			"/hardDeleteMyStationsByIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("hardDeleteMyStationsByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.station.hardDeleteMyStationsByIds"),
				},
				defaultMiddlewares,
				stationModule.Binder.BindHardDeleteMyStationsByIds(
					stationModule.Controller.HardDeleteMyStationsByIds,
				),
			)...,
		)
	}
}
