package developmentroutes

import (
	"time"

	"github.com/gin-gonic/gin"

	interceptors "github.com/HiIamJeff67/notezy-backend/app/interceptors"
	middlewares "github.com/HiIamJeff67/notezy-backend/app/middlewares"
	enums "github.com/HiIamJeff67/notezy-backend/app/models/schemas/enums"
	modules "github.com/HiIamJeff67/notezy-backend/app/modules"
)

func configureDevelopmentStationRoutes(router *gin.RouterGroup) {
	if router == nil {
		router = DevelopmentAPIRouterGroup
	}

	stationModule := modules.NewStationModule()

	stationRoutes := router.Group("/station")
	defaultMiddlewares := []gin.HandlerFunc{
		middlewares.UnauthorizedRateLimitMiddleware(),
		middlewares.TimeoutMiddleware(3 * time.Second),
		middlewares.AuthMiddleware(),
		interceptors.ShareableResponseWriterInterceptor(
			interceptors.RefreshTokenInterceptor,
			interceptors.EmbeddedInterceptor,
		),
	}
	{
		stationRoutes.GET(
			"/getMyStationById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("getMyStationById"),
					middlewares.ApplyMeterMiddleware("server.requests.station.getMyStationById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				stationModule.Binder.BindGetMyStationById(
					stationModule.Controller.GetMyStationById,
				),
			)...,
		)
		stationRoutes.GET(
			"/getAllMyStations",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("getAllMyStations"),
					middlewares.ApplyMeterMiddleware("server.requests.station.getAllMyStations"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				stationModule.Binder.BindGetAllMyStations(
					stationModule.Controller.GetAllMyStations,
				),
			)...,
		)
		stationRoutes.POST(
			"/createStation",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("createStation"),
					middlewares.ApplyMeterMiddleware("server.requests.station.createStation"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				stationModule.Binder.BindCreateStation(
					stationModule.Controller.CreateStation,
				),
			)...,
		)
		stationRoutes.POST(
			"/createStations",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("createStations"),
					middlewares.ApplyMeterMiddleware("server.requests.station.createStations"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				stationModule.Binder.BindCreateStations(
					stationModule.Controller.CreateStations,
				),
			)...,
		)
		stationRoutes.PUT(
			"/updateMyStationById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("updateMyStationById"),
					middlewares.ApplyMeterMiddleware("server.requests.station.updateMyStationById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Admin),
				),
				stationModule.Binder.BindUpdateMyStationById(
					stationModule.Controller.UpdateMyStationById,
				),
			)...,
		)
		stationRoutes.PUT(
			"/updateMyStationsByIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("updateMyStationsByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.station.updateMyStationsByIds"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Admin),
				),
				stationModule.Binder.BindUpdateMyStationsByIds(
					stationModule.Controller.UpdateMyStationsByIds,
				),
			)...,
		)
		stationRoutes.PATCH(
			"/restoreMyStationById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("restoreMyStationById"),
					middlewares.ApplyMeterMiddleware("server.requests.station.restoreMyStationById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Owner),
				),
				stationModule.Binder.BindRestoreMyStationById(
					stationModule.Controller.RestoreMyStationById,
				),
			)...,
		)
		stationRoutes.PATCH(
			"/restoreMyStationsByIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("restoreMyStationsByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.station.restoreMyStationsByIds"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Owner),
				),
				stationModule.Binder.BindRestoreMyStationsByIds(
					stationModule.Controller.RestoreMyStationsByIds,
				),
			)...,
		)
		stationRoutes.DELETE(
			"/deleteMyStationById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("deleteMyStationById"),
					middlewares.ApplyMeterMiddleware("server.requests.station.deleteMyStationById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				stationModule.Binder.BindDeleteMyStationById(
					stationModule.Controller.DeleteMyStationById,
				),
			)...,
		)
		stationRoutes.DELETE(
			"/deleteMyStationsByIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("deleteMyStationsByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.station.deleteMyStationsByIds"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Owner),
				),
				stationModule.Binder.BindDeleteMyStationsByIds(
					stationModule.Controller.DeleteMyStationsByIds,
				),
			)...,
		)
		stationRoutes.DELETE(
			"/hardDeleteMyStationById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("hardDeleteMyStationById"),
					middlewares.ApplyMeterMiddleware("server.requests.station.hardDeleteMyStationById"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Owner),
				),
				stationModule.Binder.BindHardDeleteMyStationById(
					stationModule.Controller.HardDeleteMyStationById,
				),
			)...,
		)
		stationRoutes.DELETE(
			"/hardDeleteMyStationsByIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("hardDeleteMyStationsByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.station.hardDeleteMyStationsByIds"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Owner),
				),
				stationModule.Binder.BindHardDeleteMyStationsByIds(
					stationModule.Controller.HardDeleteMyStationsByIds,
				),
			)...,
		)
		/* ============================== Routes for Visualization ============================== */

		stationRoutes.GET(
			"/visualizeMyTotalCount",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("visualizeMyTotalCount"),
					middlewares.ApplyMeterMiddleware("server.requests.station.visualizeMyTotalCount"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				stationModule.Binder.BindVisualizeMyTotalCount(
					stationModule.Controller.VisualizeMyTotalCount,
				),
			)...,
		)
		/* ============================== Routes for Station Permissions ============================== */

		stationRoutes.GET(
			"/:stationId/permissions/:userPublicId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("getMyStationPermission"),
					middlewares.ApplyMeterMiddleware("server.requests.station.getMyStationPermission"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				stationModule.Binder.BindGetMyStationPermission(
					stationModule.Controller.GetMyStationPermission,
				),
			)...,
		)
		stationRoutes.POST(
			"/:stationId/permissions/:userPublicId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("createMyStationPermission"),
					middlewares.ApplyMeterMiddleware("server.requests.station.createMyStationPermission"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Admin),
				),
				stationModule.Binder.BindCreateMyStationPermission(
					stationModule.Controller.CreateMyStationPermission,
				),
			)...,
		)
		stationRoutes.PUT(
			"/:stationId/permissions/:userPublicId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("upsertMyStationPermission"),
					middlewares.ApplyMeterMiddleware("server.requests.station.upsertMyStationPermission"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Admin),
				),
				stationModule.Binder.BindUpsertMyStationPermission(
					stationModule.Controller.UpsertMyStationPermission,
				),
			)...,
		)
		stationRoutes.PUT(
			"/:stationId/permissions",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("upsertMyStationPermissions"),
					middlewares.ApplyMeterMiddleware("server.requests.station.upsertMyStationPermissions"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Admin),
				),
				stationModule.Binder.BindUpsertMyStationPermissions(
					stationModule.Controller.UpsertMyStationPermissions,
				),
			)...,
		)
		stationRoutes.PATCH(
			"/:stationId/permissions/:userPublicId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("updateMyStationPermission"),
					middlewares.ApplyMeterMiddleware("server.requests.station.updateMyStationPermission"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Admin),
				),
				stationModule.Binder.BindUpdateMyStationPermission(
					stationModule.Controller.UpdateMyStationPermission,
				),
			)...,
		)
		stationRoutes.POST(
			"/:stationId/ownership-transfer",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("transferMyStationOwnership"),
					middlewares.ApplyMeterMiddleware("server.requests.station.transferMyStationOwnership"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Owner),
				),
				stationModule.Binder.BindTransferMyStationOwnership(
					stationModule.Controller.TransferMyStationOwnership,
				),
			)...,
		)
		stationRoutes.DELETE(
			"/:stationId/permissions/:userPublicId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("deleteMyStationPermission"),
					middlewares.ApplyMeterMiddleware("server.requests.station.deleteMyStationPermission"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Admin),
				),
				stationModule.Binder.BindDeleteMyStationPermission(
					stationModule.Controller.DeleteMyStationPermission,
				),
			)...,
		)
		stationRoutes.DELETE(
			"/:stationId/permissions",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("deleteMyStationPermissions"),
					middlewares.ApplyMeterMiddleware("server.requests.station.deleteMyStationPermissions"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Admin),
				),
				stationModule.Binder.BindDeleteMyStationPermissions(
					stationModule.Controller.DeleteMyStationPermissions,
				),
			)...,
		)
		stationRoutes.DELETE(
			"/:stationId/leave",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("leaveMyStation"),
					middlewares.ApplyMeterMiddleware("server.requests.station.leaveMyStation"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				stationModule.Binder.BindLeaveMyStation(
					stationModule.Controller.LeaveMyStation,
				),
			)...,
		)
		stationRoutes.DELETE(
			"/leave",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("leaveMyStations"),
					middlewares.ApplyMeterMiddleware("server.requests.station.leaveMyStations"),
				},
				append(
					defaultMiddlewares,
					middlewares.AllowedPermissionsAbove(enums.AccessControlPermission_Read),
				),
				stationModule.Binder.BindLeaveMyStations(
					stationModule.Controller.LeaveMyStations,
				),
			)...,
		)
	}
}
