package developmentroutes

import (
	"time"

	"github.com/gin-gonic/gin"

	interceptors "github.com/HiIamJeff67/notezy-backend/app/interceptors"
	middlewares "github.com/HiIamJeff67/notezy-backend/app/middlewares"
	modules "github.com/HiIamJeff67/notezy-backend/app/modules"
)

func configureDevelopmentSubShelfRoutes(router *gin.RouterGroup) {
	if router == nil {
		router = DevelopmentAPIRouterGroup
	}

	subShelfModule := modules.NewSubShelfModule()

	subShelfRoutes := router.Group("/subShelf")
	defaultMiddlewares := []gin.HandlerFunc{
		middlewares.UnauthorizedRateLimitMiddleware(),
		middlewares.TimeoutMiddleware(1 * time.Second),
		middlewares.AuthMiddleware(),
		interceptors.ShareableResponseWriterInterceptor(
			interceptors.RefreshTokenInterceptor,
			interceptors.EmbeddedInterceptor,
		),
	}
	{
		subShelfRoutes.GET(
			"/getMySubShelfById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("getMySubShelfById"),
					middlewares.ApplyMeterMiddleware("server.requests.subShelf.getMySubShelfById"),
				},
				defaultMiddlewares,
				subShelfModule.Binder.BindGetMySubShelfById(
					subShelfModule.Controller.GetMySubShelfById,
				),
			)...,
		)
		subShelfRoutes.GET(
			"/getMySubShelvesByPrevSubShelfId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("getMySubShelvesByPrevSubShelfId"),
					middlewares.ApplyMeterMiddleware("server.requests.subShelf.getMySubShelvesByPrevSubShelfId"),
				},
				defaultMiddlewares,
				subShelfModule.Binder.BindGetMySubShelvesByPrevSubShelfId(
					subShelfModule.Controller.GetMySubShelvesByPrevSubShelfId,
				),
			)...,
		)
		subShelfRoutes.GET(
			"/getAllMySubShelvesByRootShelfId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("getAllMySubShelvesByRootShelfId"),
					middlewares.ApplyMeterMiddleware("server.requests.subShelf.getAllMySubShelvesByRootShelfId"),
				},
				defaultMiddlewares,
				subShelfModule.Binder.BindGetAllMySubShelvesByRootShelfId(
					subShelfModule.Controller.GetAllMySubShelvesByRootShelfId,
				),
			)...,
		)
		subShelfRoutes.GET(
			"/getMySubShelvesAndItemsByPrevSubShelfId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("getMySubShelvesAndItemsByPrevSubShelfId"),
					middlewares.ApplyMeterMiddleware("server.requests.subShelf.getMySubShelvesAndItemsByPrevSubShelfId"),
				},
				defaultMiddlewares,
				subShelfModule.Binder.BindGetMySubShelvesAndItemsByPrevSubShelfId(
					subShelfModule.Controller.GetMySubShelvesAndItemsByPrevSubShelfId,
				),
			)...,
		)
		subShelfRoutes.POST(
			"/createSubShelfByRootShelfId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("createSubShelfByRootShelfId"),
					middlewares.ApplyMeterMiddleware("server.requests.subShelf.createSubShelfByRootShelfId"),
				},
				defaultMiddlewares,
				subShelfModule.Binder.BindCreateSubShelfByRootShelfId(
					subShelfModule.Controller.CreateSubShelfByRootShelfId,
				),
			)...,
		)
		subShelfRoutes.POST(
			"/createSubShelvesByRootShelfIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("createSubShelvesByRootShelfIds"),
					middlewares.ApplyMeterMiddleware("server.requests.subShelf.CreateSubShelvesByRootShelfIds"),
				},
				defaultMiddlewares,
				subShelfModule.Binder.BindCreateSubShelvesByRootShelfIds(
					subShelfModule.Controller.CreateSubShelvesByRootShelfIds,
				),
			)...,
		)
		subShelfRoutes.PUT(
			"/updateMySubShelfById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("updateMySubShelfById"),
					middlewares.ApplyMeterMiddleware("server.requests.subShelf.updateMySubShelfById"),
				},
				defaultMiddlewares,
				subShelfModule.Binder.BindUpdateMySubShelfById(
					subShelfModule.Controller.UpdateMySubShelfById,
				),
			)...,
		)
		subShelfRoutes.PUT(
			"/updateMySubShelvesByIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("updateMySubShelvesByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.subShelf.UpdateMySubShelvesByIds"),
				},
				defaultMiddlewares,
				subShelfModule.Binder.BindUpdateMySubShelvesByIds(
					subShelfModule.Controller.UpdateMySubShelvesByIds,
				),
			)...,
		)
		subShelfRoutes.PUT(
			"/moveMySubShelf",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("moveMySubShelf"),
					middlewares.ApplyMeterMiddleware("server.requests.subShelf.moveMySubShelf"),
				},
				defaultMiddlewares,
				subShelfModule.Binder.BindMoveMySubShelf(
					subShelfModule.Controller.MoveMySubShelf,
				),
			)...,
		)
		subShelfRoutes.PUT(
			"/moveMySubShelvesByRootShelfId",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("moveMySubShelvesByRootShelfId"),
					middlewares.ApplyMeterMiddleware("server.requests.subShelf.moveMySubShelvesByRootShelfId"),
				},
				defaultMiddlewares,
				subShelfModule.Binder.BindMoveMySubShelvesByRootShelfId(
					subShelfModule.Controller.MoveMySubShelvesByRootShelfId,
				),
			)...,
		)
		subShelfRoutes.PUT(
			"/moveMySubShelvesByRootShelfIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("moveMySubShelvesByRootShelfIds"),
					middlewares.ApplyMeterMiddleware("server.requests.subShelf.moveMySubShelvesByRootShelfIds"),
				},
				defaultMiddlewares,
				subShelfModule.Binder.BindMoveMySubShelvesByRootShelfIds(
					subShelfModule.Controller.MoveMySubShelvesByRootShelfIds,
				),
			)...,
		)
		subShelfRoutes.PATCH(
			"/restoreMySubShelfById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("restoreMySubShelfById"),
					middlewares.ApplyMeterMiddleware("server.requests.subShelf.restoreMySubShelfById"),
				},
				defaultMiddlewares,
				subShelfModule.Binder.BindRestoreMySubShelfById(
					subShelfModule.Controller.RestoreMySubShelfById,
				),
			)...,
		)
		subShelfRoutes.PATCH(
			"/restoreMySubShelvesByIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("restoreMySubShelvesByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.subShelf.restoreMySubShelvesByIds"),
				},
				defaultMiddlewares,
				subShelfModule.Binder.BindRestoreMySubShelvesByIds(
					subShelfModule.Controller.RestoreMySubShelvesByIds,
				),
			)...,
		)
		subShelfRoutes.DELETE(
			"/deleteMySubShelfById",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("deleteMySubShelfById"),
					middlewares.ApplyMeterMiddleware("server.requests.subShelf.deleteMySubShelfById"),
				},
				defaultMiddlewares,
				subShelfModule.Binder.BindDeleteMySubShelfById(
					subShelfModule.Controller.DeleteMySubShelfById,
				),
			)...,
		)
		subShelfRoutes.DELETE(
			"/deleteMySubShelvesByIds",
			middlewares.RepositionMiddleware(
				[]gin.HandlerFunc{
					middlewares.ApplyTracerMiddleware("deleteMySubShelvesByIds"),
					middlewares.ApplyMeterMiddleware("server.requests.subShelf.deleteMySubShelvesByIds"),
				},
				defaultMiddlewares,
				subShelfModule.Binder.BindDeleteMySubShelvesByIds(
					subShelfModule.Controller.DeleteMySubShelvesByIds,
				),
			)...,
		)
	}
}
