# Source: badge.graphql
type PublicBadge {
  # id: UUID!
  publicId: UUID! # the encoded of this field is the identifier of the PublicBadge
  title: String!
  description: String!
  type: BadgeType!
  imageURL: String
  createdAt: Time!
}

# Source: block.graphql
type PrivateBlock {
    id: UUID!
    blockPackId: UUID!
    parentBlockId: UUID
    prevBlockId: UUID
    nextBlockId: UUID
    type: BlockType!
    props: DatatypeJSON!
    content: DatatypeJSON!
    updatedAt: Time!
    createdAt: Time!

    # relations
    childrenIds: [UUID!]!
}

# Source: block_pack.graphql
type PrivateBlockPack {
  id: UUID!
  parentSubShelfId: UUID!
  name: String!
  icon: SupportedIcon
  headerBackgroundURL: String
  blockCount: Int64!
  deletedAt: Time
  updatedAt: Time!
  createdAt: Time!

  # relations
  blockIds: [UUID!]!
}

# Source: enums/access_control_permission_enum.graphql
enum AccessControlPermission {
  Owner
  Admin
  Write
  Read
}

# Source: enums/badge_type_enum.graphql
enum BadgeType {
  Diamond
  Golden
  Silver
  Bronze
  Steel
}

# Source: enums/block_type_enum.graphql
enum BlockType {
    BlockType_Paragraph # paragraph
	BlockType_Heading, # heading
	BlockType_Quote, # quote
	BlockType_BulletListItem, # bulletListItem
	BlockType_NumberedListItem, # numberedListItem
	BlockType_CheckListItem, # checkListItem
	BlockType_ToggleListItem, # toggleListItem
	BlockType_Image, # image
	BlockType_Video, # video
	BlockType_Audio, # audio
	BlockType_File, # file
	BlockType_Table, # table
	BlockType_CodeBlock, # codeBlock
}

# Source: enums/country_code_enum.graphql
enum CountryCode {
  COUNTRY_CODE_886 # Taiwan
  COUNTRY_CODE_81 # Japan
  COUNTRY_CODE_60 # Malaysia
  COUNTRY_CODE_65 # Singapore
  COUNTRY_CODE_86 # China
  COUNTRY_CODE_1 # NANP
  COUNTRY_CODE_44 # UK
  COUNTRY_CODE_61 # Australia
}

# Source: enums/country_enum.graphql
enum Country {
  Taiwan
  Japan
  Malaysia
  Singapore
  China
  UnitedStatesOfAmerica
  UnitedKingdom
  Australia
  Canada
}

# Source: enums/item_type_enum.graphql
enum ItemType {
  ItemType_BlockPack
  ItemType_Material
}

# Source: enums/language_enum.graphql
enum Language {
  English
  TraditionalChinese
  SimpleChinese
  Japanese
  Korean
}

# Source: enums/material_content_type_enum.graphql
enum MaterialContentType {
  None
  Application_JSON
  Application_PDF
  Text_Plain
  Text_HTML
  Text_Markdown
  Image_PNG
  Image_JPG
  Image_JPEG
  Image_GIF
  Image_SVG
  Image_WebP
  Video_MP4
  Video_WebM
  Audio_Mpeg
}

# Source: enums/routine_period_enum.graphql
enum RoutinePeriod {
  RoutinePeriod_Daily
  RoutinePeriod_Weekly
  RoutinePeriod_Monthly
}

# Source: enums/routine_status_enum.graphql
enum RoutineStatus {
  RoutineStatus_Scheduled
  RoutineStatus_InProgress
  RoutineStatus_Completed
  RoutineStatus_OverDue
}

# Source: enums/routine_task_purpose_enum.graphql
enum RoutineTaskPurpose {
  RoutineTaskPurpose_CreateRootShelf
  RoutineTaskPurpose_UpdateRootShelf
  RoutineTaskPurpose_ResetRootShelf
  RoutineTaskPurpose_CreateSubShelf
  RoutineTaskPurpose_UpdateSubShelf
  RoutineTaskPurpose_ResetSubShelf
  RoutineTaskPurpose_CreateBlockPack
  RoutineTaskPurpose_UpdateBlockPack
  RoutineTaskPurpose_ResetBlockPack
  RoutineTaskPurpose_AppendBlock
  RoutineTaskPurpose_UpdateBlock
  RoutineTaskPurpose_ResetBlock
  RoutineTaskPurpose_CreateRoutine
  RoutineTaskPurpose_UpdateRoutine
}

# Source: enums/routine_task_record_error_code_enum.graphql
enum RoutineTaskRecordErrorCode {
  RoutineTaskRecordErrorCode_PermissionDenied
  RoutineTaskRecordErrorCode_PayloadInvalid
  RoutineTaskRecordErrorCode_TargetNotFound
  RoutineTaskRecordErrorCode_PlanLimitExceeded
  RoutineTaskRecordErrorCode_HandlerFailed
  RoutineTaskRecordErrorCode_DatabaseError
  RoutineTaskRecordErrorCode_Timeout
  RoutineTaskRecordErrorCode_Canceled
  RoutineTaskRecordErrorCode_Unknown
}

# Source: enums/routine_task_record_status_enum.graphql
enum RoutineTaskRecordStatus {
  RoutineTaskRecordStatus_Running
  RoutineTaskRecordStatus_Success
  RoutineTaskRecordStatus_Failed
  RoutineTaskRecordStatus_Cancel
}

# Source: enums/routine_task_status_enum.graphql
enum RoutineTaskStatus {
  RoutineTaskStatus_Idle
  RoutineTaskStatus_Waiting
  RoutineTaskStatus_Running
  RoutineTaskStatus_Pause
}

# Source: enums/supported_icon_enum.graphql
enum SupportedIcon {
  SupportedIcon_GrinningFace
  SupportedIcon_SmilingFaceWithSmilingEyes
  SupportedIcon_RedHeart
  SupportedIcon_Fire
  SupportedIcon_Star
  SupportedIcon_Books
  SupportedIcon_Notebook
  SupportedIcon_PencilPaper
  SupportedIcon_Lightbulb
  SupportedIcon_Rocket
  SupportedIcon_CheckMark
  SupportedIcon_Pin
  SupportedIcon_FolderOpen
  SupportedIcon_Calendar
  SupportedIcon_Clock
}

# Source: enums/user_gender_enum.graphql
enum UserGender {
  Male
  Female
  PreferNotToSay
}

# Source: enums/user_plan_enum.graphql
enum UserPlan {
  Enterprise
  Ultimate
  Pro
  Free
}

# Source: enums/user_role_enum.graphql
enum UserRole {
  Admin
  Normal
  Guest
}

# Source: enums/user_status_enum.graphql
enum UserStatus {
  Online
  AFK
  DoNotDisturb
  Offline
}

# Source: fields.graphql
# every schemas or graphql types which want to be searchable
# are required to inheritence the structure (of cursor-based pagination) here

# =============== Search Filters (part of Input) =============== #
# input ExampleSearchFilters {}

# =============== Search Sort By (part of Input) =============== #
# enum ExampleSearchSortBy {
#     RELEVANCE
# }

# =============== Search Sort Order (part of Input) =============== #
# Note that this field is fixed, and should not build another one for customization
enum SearchSortOrder {
  ASC
  DESC
}

# ==================== Search Input ==================== #
# input ExampleSearchInput {
#     query: String!
#     after: String
#     first: Int = 10
#     filters: SearchFilters
#     sortBy: SearchSortBy = RELEVANCE
#     sortOrder: SearchSortOrder = DESC
# }

# =============== Current Edge (part of Output) =============== #
interface SearchEdge {
  encodedSearchCursor: String!
  # node: the data of the result, this should be implement in each models require search functionality
}

# =============== Page Info (part of Output) =============== #
type SearchPageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startEncodedSearchCursor: String
  endEncodedSearchCursor: String
}

# =============== Search Output (Connection) =============== #
interface SearchConnection {
  searchPageInfo: SearchPageInfo!
  totalCount: Int!
  searchTime: Float!
}

# Source: item.graphql
type PrivateItem {
    id: UUID!
    parentSubShelfId: UUID!
    rootShelfId: UUID!
    type: ItemType!
    deletedAt: Time
    updatedAt: Time!
    createdAt: Time!

    # relations
    routineIds: [UUID!]!
}

# Source: material.graphql
type PrivateMaterial {
  id: UUID!
  parentSubShelfId: UUID!
  name: String!
  size: Int64!
  contentType: MaterialContentType!
  parseMediaType: String!
  deletedAt: Time
  updatedAt: Time!
  createdAt: Time!
}

# Source: query.graphql
type Query {
  searchUsers(input: SearchUserInput!): SearchUserConnection!
  searchThemes(input: SearchThemeInput!): SearchThemeConnection!
  searchRootShelves(input: SearchRootShelfInput!): SearchRootShelfConnection!
  searchSubShelves(input: SearchSubShelfInput!): SearchSubShelfConnection!
  searchItems(input: SearchItemInput!): SearchItemConnection!
  searchMaterials(input: SearchMaterialInput!): SearchMaterialConnection!
  searchBlockPacks(input: SearchBlockPackInput!): SearchBlockPackConnection!
  searchBlocks(input: SearchBlockInput!): SearchBlockConnection!
  searchStations(input: SearchStationInput!): SearchStationConnection!
  searchRoutines(input: SearchRoutineInput!): SearchRoutineConnection!
  searchRoutineTags(input: SearchRoutineTagInput!): SearchRoutineTagConnection!
  searchRoutineTasks(input: SearchRoutineTaskInput!): SearchRoutineTaskConnection!
  searchRoutineTaskRecords(input: SearchRoutineTaskRecordInput!): SearchRoutineTaskRecordConnection!
}

# type Mutation {}

# type Subscription {}

# Source: root_shelf.graphql
type PrivateRootShelf {
  id: UUID!
  name: String!
  permission: AccessControlPermission!
  subShelfCount: Int64!
  itemCount: Int64!
  lastAnalyzedAt: Time!
  deletedAt: Time
  updatedAt: Time!
  createdAt: Time!

  # relations
  owner: PublicUser!
  sharers: [PublicUser!]!
  itemIds: [UUID!]!
}

# Source: routine.graphql
type PrivateRoutine {
  id: UUID!
  stationId: UUID!
  title: String!
  description: String!
  status: RoutineStatus!
  isPinned: Boolean!
  scheduledStartAt: Time!
  scheduledEndAt: Time!
  period: RoutinePeriod
  timezone: String!
  deletedAt: Time
  updatedAt: Time!
  createdAt: Time!

  # relations
  tagIds: [UUID!]!
  taskIds: [UUID!]!
  itemIds: [UUID!]!
}

type PrivateSearchableRoutine {
  id: UUID!
  stationId: UUID!
  title: String!
  status: RoutineStatus!
  isPinned: Boolean!
  scheduledStartAt: Time!
  scheduledEndAt: Time!
  period: RoutinePeriod
  timezone: String!
  deletedAt: Time
  updatedAt: Time!
  createdAt: Time!

  # relations
  tagIds: [UUID!]!
  taskIds: [UUID!]!
  itemIds: [UUID!]! 
}

# Source: routine_tag.graphql
type PrivateRoutineTag {
  id: UUID!
  name: String!
  color: String!
  icon: SupportedIcon
  updatedAt: Time!
  createdAt: Time!
}

# Source: routine_task.graphql
type PrivateRoutineTask {
  id: UUID!
  routineId: UUID!
  title: String!
  purpose: RoutineTaskPurpose!
  payload: RawJSON!
  costUnit: Int64!
  priority: Int32!
  status: RoutineTaskStatus!
  attempts: Int32!
  maxAttempts: Int32!
  period: RoutinePeriod
  nextScheduledAt: Time!
  scheduledAt: Time!
  actualStartedAt: Time
  actualEndedAt: Time
  updatedAt: Time!
  createdAt: Time!
}

# Source: routine_task_record.graphql
type PrivateRoutineTaskRecord {
  id: UUID!
  routineTaskId: UUID!
  purpose: RoutineTaskPurpose!
  status: RoutineTaskRecordStatus!
  errorCode: RoutineTaskRecordErrorCode
  errorReason: String
  costUnit: Int64!
  totalAttempts: Int64!
  scheduledAt: Time!
  actualStartedAt: Time
  actualEndedAt: Time
  updatedAt: Time!
  createdAt: Time!
}

# Source: scalar.graphql
scalar Int32
scalar Int64
scalar UUID
scalar Time
scalar Base64Bytes
scalar RawJSON
scalar DatatypeJSON

# Source: search_badges.graphql
# =============== Search Filters & SortBy & SortOrder =============== #

input SearchBadgeFilters {
  type: BadgeType
}

enum SearchBadgeSortBy {
  RELEVANCE
  TITLE
  CREATED_AT
}

input SearchBadgeInput {
  query: String!
  after: String
  first: Int = 10
  filters: SearchBadgeFilters
  sortBy: SearchBadgeSortBy = RELEVANCE
  sortOrder: SearchSortOrder = DESC
}

# =============== Search Cursor Fields =============== #

# type SearchBadgeEnvironmentAttributes {}

input SearchBadgeCursorFields {
  publicId: UUID!
  # environmentAttributes: SearchBadgeEnvironmentAttributes
}

# =============== Search Edge & Connection =============== #

type SearchBadgeEdge implements SearchEdge {
  encodedSearchCursor: String! # the search identifier
  node: PublicBadge! # the search result
}

type SearchBadgeConnection implements SearchConnection {
  searchEdges: [SearchBadgeEdge!]!
  searchPageInfo: SearchPageInfo!
  totalCount: Int!
  searchTime: Float!
}

# Source: search_block.graphql
# =============== Search SortBy & Input =============== #

enum SearchBlockSortBy {
    RELEVANCE
    TYPE
    LAST_UPDATE
    CREATED_AT
}

input SearchBlockInput {
    query: String!
    after: String
    first: Int = 10
    sortBy: SearchBlockSortBy = RELEVANCE
    sortOrder: SearchSortOrder = DESC
}

# =============== Search Cursor Fields =============== #

input SearchBlockCursorFields {
    id: UUID!
}

# =============== Search Edge & Connection =============== #

type SearchBlockEdge implements SearchEdge {
    encodedSearchCursor: String!
    node: PrivateBlock!
}

type SearchBlockConnection implements SearchConnection {
    searchEdges: [SearchBlockEdge!]!
    searchPageInfo: SearchPageInfo!
    totalCount: Int!
    searchTime: Float!
}

# Source: search_block_packs.graphql
# =============== Search SortBy & Input =============== #

enum SearchBlockPackSortBy {
  RELEVANCE
  NAME
  BLOCK_COUNT
  LAST_UPDATE
  CREATED_AT
}

input SearchBlockPackInput {
  parentSubShelfId: UUID
  rootShelfId: UUID
  query: String!
  isDeletedAt: Boolean
  after: String
  first: Int = 10
  sortBy: SearchBlockPackSortBy = RELEVANCE
  sortOrder: SearchSortOrder = DESC
}

# =============== Search Cursor Fields =============== #

input SearchBlockPackCursorFields {
  id: UUID!
}

# =============== Search Edge & Connection =============== #

type SearchBlockPackEdge implements SearchEdge {
  encodedSearchCursor: String!
  node: PrivateBlockPack!
}

type SearchBlockPackConnection implements SearchConnection {
  searchEdges: [SearchBlockPackEdge!]!
  searchPageInfo: SearchPageInfo!
  totalCount: Int!
  searchTime: Float!
}

# Source: search_items.graphql
# =============== Search SortBy & Input =============== #

enum SearchItemSortBy {
    RELEVANCE
    TYPE
    LAST_UPDATE
    CREATED_AT
}

input SearchItemInput {
    parentSubShelfId: UUID
    rootShelfId: UUID
    query: String!
    isDeletedAt: Boolean
    after: String
    first: Int = 10
    sortBy: SearchItemSortBy = RELEVANCE
    sortOrder: SearchSortOrder = DESC
}

# =============== Search Cursor Fields =============== #

input SearchItemCursorFields {
    id: UUID!
}

# =============== Search Edge & Connection =============== #

type SearchItemEdge implements SearchEdge {
    encodedSearchCursor: String!
    node: PrivateItem!
}

type SearchItemConnection implements SearchConnection {
    searchEdges: [SearchItemEdge!]!
    searchPageInfo: SearchPageInfo!
    totalCount: Int!
    searchTime: Float!
}

# Source: search_materials.graphql
# =============== Search SortBy & Input =============== #

enum SearchMaterialSortBy {
  RELEVANCE
  NAME
  SIZE
  CONTENT_TYPE
  LAST_UPDATE
  CREATED_AT
}

input SearchMaterialInput {
  parentSubShelfId: UUID
  rootShelfId: UUID
  query: String!
  isDeletedAt: Boolean
  after: String
  first: Int = 10
  sortBy: SearchMaterialSortBy = RELEVANCE
  sortOrder: SearchSortOrder = DESC
}

# =============== Search Cursor Fields =============== #

input SearchMaterialCursorFields {
  id: UUID!
}

# =============== Search Edge & Connection =============== #

type SearchMaterialEdge implements SearchEdge {
  encodedSearchCursor: String!
  node: PrivateMaterial!
}

type SearchMaterialConnection implements SearchConnection {
  searchEdges: [SearchMaterialEdge!]!
  searchPageInfo: SearchPageInfo!
  totalCount: Int!
  searchTime: Float!
}

# Source: search_root_shelves.graphql
# =============== Search SortBy & Input =============== #

enum SearchRootShelfSortBy {
  RELEVANCE
  NAME
  LAST_UPDATE
  CREATED_AT
}

input SearchRootShelfInput {
  query: String!
  isDeletedAt: Boolean
  after: String
  first: Int = 10
  sortBy: SearchRootShelfSortBy = RELEVANCE
  sortOrder: SearchSortOrder = DESC
}

# =============== Search Cursor Fields =============== #

# type SearchRootShelfEnvironmentAttributes {}

input SearchRootShelfCursorFields {
  id: UUID!
  # environmentAttributes: SearchRootShelfEnvironmentAttributes
}

# =============== Search Edge & Connection =============== #

type SearchRootShelfEdge implements SearchEdge {
  encodedSearchCursor: String!
  node: PrivateRootShelf!
}

type SearchRootShelfConnection implements SearchConnection {
  searchEdges: [SearchRootShelfEdge!]!
  searchPageInfo: SearchPageInfo!
  totalCount: Int!
  searchTime: Float!
}

# Source: search_routine_tags.graphql
# =============== Search SortBy & Input =============== #

enum SearchRoutineTagSortBy {
  RELEVANCE
  NAME
  LAST_UPDATE
  CREATED_AT
}

input SearchRoutineTagInput {
  query: String!
  after: String
  first: Int = 10
  sortBy: SearchRoutineTagSortBy = RELEVANCE
  sortOrder: SearchSortOrder = DESC
}

# =============== Search Cursor Fields =============== #

input SearchRoutineTagCursorFields {
  id: UUID!
}

# =============== Search Edge & Connection =============== #

type SearchRoutineTagEdge implements SearchEdge {
  encodedSearchCursor: String!
  node: PrivateRoutineTag!
}

type SearchRoutineTagConnection implements SearchConnection {
  searchEdges: [SearchRoutineTagEdge!]!
  searchPageInfo: SearchPageInfo!
  totalCount: Int!
  searchTime: Float!
}

# Source: search_routine_task_records.graphql
# =============== Search SortBy & Input =============== #

enum SearchRoutineTaskRecordSortBy {
  RELEVANCE
  PURPOSE
  STATUS
  COST_UNIT
  TOTAL_ATTEMPTS
  SCHEDULED_AT
  ACTUAL_STARTED_AT
  ACTUAL_ENDED_AT
  LAST_UPDATE
  CREATED_AT
}

input SearchRoutineTaskRecordInput {
  routineTaskIds: [UUID!]!
  query: String!
  after: String
  first: Int = 10
  sortBy: SearchRoutineTaskRecordSortBy = RELEVANCE
  sortOrder: SearchSortOrder = DESC
}

# =============== Search Cursor Fields =============== #

input SearchRoutineTaskRecordCursorFields {
  id: UUID!
}

# =============== Search Edge & Connection =============== #

type SearchRoutineTaskRecordEdge implements SearchEdge {
  encodedSearchCursor: String!
  node: PrivateRoutineTaskRecord!
}

type SearchRoutineTaskRecordConnection implements SearchConnection {
  searchEdges: [SearchRoutineTaskRecordEdge!]!
  searchPageInfo: SearchPageInfo!
  totalCount: Int!
  searchTime: Float!
}

# Source: search_routine_tasks.graphql
# =============== Search SortBy & Input =============== #

enum SearchRoutineTaskSortBy {
  RELEVANCE
  TITLE
  PURPOSE
  PRIORITY
  STATUS
  ATTEMPTS
  MAX_ATTEMPTS
  SCHEDULED_AT
  ACTUAL_STARTED_AT
  ACTUAL_ENDED_AT
  LAST_UPDATE
  CREATED_AT
}

input SearchRoutineTaskInput {
  routineIds: [UUID!]!
  query: String!
  after: String
  first: Int = 10
  sortBy: SearchRoutineTaskSortBy = RELEVANCE
  sortOrder: SearchSortOrder = DESC
}

# =============== Search Cursor Fields =============== #

input SearchRoutineTaskCursorFields {
  id: UUID!
}

# =============== Search Edge & Connection =============== #

type SearchRoutineTaskEdge implements SearchEdge {
  encodedSearchCursor: String!
  node: PrivateRoutineTask!
}

type SearchRoutineTaskConnection implements SearchConnection {
  searchEdges: [SearchRoutineTaskEdge!]!
  searchPageInfo: SearchPageInfo!
  totalCount: Int!
  searchTime: Float!
}

# Source: search_routines.graphql
# =============== Search SortBy & Input =============== #

enum SearchRoutineSortBy {
  RELEVANCE
  TITLE
  STATUS
  SCHEDULED_START_AT
  SCHEDULED_END_AT
  PERIOD
  LAST_UPDATE
  CREATED_AT
}

input SearchRoutineInput {
  stationIds: [UUID!]!
  tagIds: [UUID!]!
  query: String!
  isDeletedAt: Boolean
  after: String
  first: Int = 10
  sortBy: SearchRoutineSortBy = RELEVANCE
  sortOrder: SearchSortOrder = DESC
}

# =============== Search Cursor Fields =============== #

input SearchRoutineCursorFields {
  id: UUID!
}

# =============== Search Edge & Connection =============== #

type SearchRoutineEdge implements SearchEdge {
  encodedSearchCursor: String!
  node: PrivateSearchableRoutine!
}

type SearchRoutineConnection implements SearchConnection {
  searchEdges: [SearchRoutineEdge!]!
  searchPageInfo: SearchPageInfo!
  totalCount: Int!
  searchTime: Float!
}

# Source: search_stations.graphql
# =============== Search SortBy & Input =============== #

enum SearchStationSortBy {
  RELEVANCE
  NAME
  ROUTINE_COUNT
  LAST_UPDATE
  CREATED_AT
}

input SearchStationInput {
  query: String!
  isDeletedAt: Boolean
  after: String
  first: Int = 10
  sortBy: SearchStationSortBy = RELEVANCE
  sortOrder: SearchSortOrder = DESC
}

# =============== Search Cursor Fields =============== #

input SearchStationCursorFields {
  id: UUID!
}

# =============== Search Edge & Connection =============== #

type SearchStationEdge implements SearchEdge {
  encodedSearchCursor: String!
  node: PrivateSearchableStation!
}

type SearchStationConnection implements SearchConnection {
  searchEdges: [SearchStationEdge!]!
  searchPageInfo: SearchPageInfo!
  totalCount: Int!
  searchTime: Float!
}

# Source: search_sub_shelves.graphql
# =============== Search SortBy & Input =============== #

enum SearchSubShelfSortBy {
  RELEVANCE
  NAME
  PATH_LENGTH
  LAST_UPDATE
  CREATED_AT
}

input SearchSubShelfInput {
  rootShelfId: UUID
  prevSubShelfId: UUID
  query: String!
  isDeletedAt: Boolean
  after: String
  first: Int = 10
  sortBy: SearchSubShelfSortBy = RELEVANCE
  sortOrder: SearchSortOrder = DESC
}

# =============== Search Cursor Fields =============== #

# type SearchSubShelfEnvironmentAttributes {}

input SearchSubShelfCursorFields {
  id: UUID!
  # environmentAttributes: SearchSubShelfEnvironmentAttributes
}

# =============== Search Edge & Connection =============== #

type SearchSubShelfEdge implements SearchEdge {
  encodedSearchCursor: String!
  node: PrivateSubShelf!
}

type SearchSubShelfConnection implements SearchConnection {
  searchEdges: [SearchSubShelfEdge!]!
  searchPageInfo: SearchPageInfo!
  totalCount: Int!
  searchTime: Float!
}

# Source: search_themes.graphql
# =============== Search Filters & SortBy & Input =============== #

input SearchThemeFilters {
  isDefault: Boolean
  downloadCountGreaterThan: Int
}

enum SearchThemeSortBy {
  RELEVANCE
  NAME
  LAST_UPDATE
  CREATED_AT
}

input SearchThemeInput {
  query: String!
  after: String
  first: Int = 10
  filters: SearchThemeFilters
  sortBy: SearchThemeSortBy = RELEVANCE
  sortOrder: SearchSortOrder = DESC
}

# =============== Search Cursor Fields =============== #

# type SearchThemeEnvironmentAttributes {}

input SearchThemeCursorFields {
  publicId: UUID!
  # environmentAttributes: SearchThemeEnvironmentAttributes
}

# =============== Search Edge & Connection =============== #

type SearchThemeEdge implements SearchEdge {
  encodedSearchCursor: String! # the search identifier
  node: PublicTheme! # the search result
}

type SearchThemeConnection implements SearchConnection {
  searchEdges: [SearchThemeEdge!]!
  searchPageInfo: SearchPageInfo!
  totalCount: Int!
  searchTime: Float!
}

# Source: search_users.graphql
# =============== Search Filters & SortBy & Input =============== #

input SearchUserFilters {
  role: UserRole
  plan: UserPlan
  status: UserStatus
  hasAvatar: Boolean
  country: Country
  isOnline: Boolean
}

enum SearchUserSortBy {
  RELEVANCE
  NAME # using this to check both the name and display name fields
  LAST_ACTIVE
  CREATED_AT
}

input SearchUserInput {
  query: String! # the input from the frontend
  rootShelfIds: [UUID!] # match users who collaborate on any accessible RootShelf
  stationIds: [UUID!] # match users who collaborate on any accessible Station
  badgePublicIds: [UUID!] # match users who have any public Badge
  after: String # base64 encoded cursor
  first: Int = 10 # the number of data we want to extract
  filters: SearchUserFilters
  sortBy: SearchUserSortBy = RELEVANCE
  sortOrder: SearchSortOrder = DESC
}

# =============== Search Cursor Fields =============== #

# type SearchUserEnvironmentAttributes {}

# use the below fields to encoded it into base64
# and included some attributes as weights of the search algorithm
# for better search experience
input SearchUserCursorFields {
  publicId: UUID!
  # environmentAttributes: SearchUserEnvironmentAttributes
  # add some weight to effect the searching result here
}

# =============== Search Edge & Connection =============== #

type SearchUserEdge implements SearchEdge {
  encodedSearchCursor: String! # the encoded search identifier
  node: PublicUser! # the search result
}

type SearchUserConnection implements SearchConnection {
  searchEdges: [SearchUserEdge!]!
  searchPageInfo: SearchPageInfo!
  totalCount: Int!
  searchTime: Float!
}

# Source: station.graphql
type PrivateStation {
  id: UUID!
  permission: AccessControlPermission!
  name: String!
  description: String!
  icon: SupportedIcon
  headerBackgroundURL: String
  routineCount: Int64!
  deletedAt: Time
  createdAt: Time!
  updatedAt: Time!
}

type PrivateSearchableStation {
  id: UUID!
  permission: AccessControlPermission!
  name: String!
  icon: SupportedIcon
  headerBackgroundURL: String
  routineCount: Int64!
  deletedAt: Time
  createdAt: Time!
  updatedAt: Time!
}

# Source: sub_shelf.graphql
type PrivateSubShelf {
  id: UUID!
  name: String!
  rootShelfId: UUID!
  prevSubShelfId: UUID
  path: [UUID!]!
  deletedAt: Time
  updatedAt: Time!
  createdAt: Time!

  # relations
  nextSubShelfIds: [UUID!]!
  itemIds: [UUID!]!
}

# Source: theme.graphql
type PublicTheme {
  # id: UUID!
  publicId: UUID! # the encoded of this field is the identifier of the PublicTheme
  name: String!
  isDark: Boolean!
  authorId: UUID!
  version: String!
  isDefault: Boolean!
  downloadURL: String
  downloadCount: Int64!
  createdAt: Time!
  updatedAt: Time!
}

# Source: user.graphql
# the complete user structure: internal/core/data/database/schemas/user_schema.go
# this schema file is only use for go graphql to improve better user experience

type PublicUser {
  # id: UUID!
  publicId: UUID! # the encoded of this field is the identifier of the PublicUser
  name: String!
  displayName: String!
  # email: String!
  # password: String!
  # refreshToken: String!
  # loginCount: Int
  # blockLoginUtil: Time!
  # userAgent: String!
  role: UserRole!
  plan: UserPlan!
  # prevStatus: UserStatus!
  status: UserStatus!
  createdAt: Time!
  # updatedAt: Time!

  # relations
  info: PublicUserInfo
}

# Source: user_info.graphql
type PublicUserInfo {
  # id: UUID!
  # userId: UUID!
  avatarURL: String
  coverBackgroundURL: String
  header: String
  introduction: String
  gender: UserGender!
  country: Country
  birthDate: Time!
  # updatedAt: Time!
}
